
export type SymbolInfo = {
    char: string;
    name: string;
};

export const allSymbols: SymbolInfo[] = [
    // Arrows
    { char: '←', name: 'leftwards arrow' },
    { char: '↑', name: 'upwards arrow' },
    { char: '→', name: 'rightwards arrow' },
    { char: '↓', name: 'downwards arrow' },
    { char: '↔', name: 'left right arrow' },
    { char: '↕', name: 'up down arrow' },
    { char: '↖', name: 'north west arrow' },
    { char: '↗', name: 'north east arrow' },
    { char: '↘', name: 'south east arrow' },
    { char: '↙', name: 'south west arrow' },
    { char: '↚', name: 'leftwards arrow with stroke' },
    { char: '↛', name: 'rightwards arrow with stroke' },
    { char: '↜', name: 'leftwards wave arrow' },
    { char: '↝', name: 'rightwards wave arrow' },
    { char: '↞', name: 'leftwards two headed arrow' },
    { char: '↟', name: 'upwards two headed arrow' },
    { char: '↠', name: 'rightwards two headed arrow' },
    { char: '↡', name: 'downwards two headed arrow' },
    { char: '↢', name: 'leftwards arrow with tail' },
    { char: '↣', name: 'rightwards arrow with tail' },
    { char: '↤', name: 'leftwards arrow from bar' },
    { char: '↥', name: 'upwards arrow from bar' },
    { char: '↦', name: 'rightwards arrow from bar' },
    { char: '↧', name: 'downwards arrow from bar' },
    { char: '↨', name: 'up down arrow with base' },
    { char: '↩', name: 'rightwards arrow with hook' },
    { char: '↪', name: 'leftwards arrow with hook' },
    { char: '↫', name: 'leftwards arrow with loop' },
    { char: '↬', name: 'rightwards arrow with loop' },
    { char: '↭', name: 'left right wave arrow' },
    { char: '↮', name: 'left right arrow with stroke' },
    { char: '↯', name: 'downwards zigzag arrow' },
    { char: '↰', name: 'upwards arrow with tip leftwards' },
    { char: '↱', name: 'upwards arrow with tip rightwards' },
    { char: '↲', name: 'downwards arrow with tip leftwards' },
    { char: '↳', name: 'downwards arrow with tip rightwards' },
    { char: '↴', name: 'rightwards arrow with corner downwards' },
    { char: '↵', name: 'downwards arrow with corner leftwards' },
    { char: '↶', name: 'anticlockwise top semicircle arrow' },
    { char: '↷', name: 'clockwise top semicircle arrow' },
    { char: '↸', name: 'north west arrow to long bar' },
    { char: '↹', name: 'leftwards arrow to bar over rightwards arrow to bar' },
    { char: '↺', name: 'anticlockwise open circle arrow' },
    { char: '↻', name: 'clockwise open circle arrow' },
    { char: '↼', name: 'leftwards harpoon with barb upwards' },
    { char: '↽', name: 'leftwards harpoon with barb downwards' },
    { char: '↾', name: 'upwards harpoon with barb rightwards' },
    { char: '↿', name: 'upwards harpoon with barb leftwards' },
    { char: '⇀', name: 'rightwards harpoon with barb upwards' },
    { char: '⇁', name: 'rightwards harpoon with barb downwards' },
    { char: '⇂', name: 'downwards harpoon with barb rightwards' },
    { char: '⇃', name: 'downwards harpoon with barb leftwards' },
    { char: '⇄', name: 'rightwards arrow over leftwards arrow' },
    { char: '⇅', name: 'upwards arrow leftwards of downwards arrow' },
    { char: '⇆', name: 'leftwards arrow over rightwards arrow' },
    { char: '⇇', name: 'leftwards paired arrows' },
    { char: '⇈', name: 'upwards paired arrows' },
    { char: '⇉', name: 'rightwards paired arrows' },
    { char: '⇊', name: 'downwards paired arrows' },
    { char: '⇋', name: 'leftwards harpoon over rightwards harpoon' },
    { char: '⇌', name: 'rightwards harpoon over leftwards harpoon' },
    { char: '⇍', name: 'leftwards double arrow with stroke' },
    { char: '⇎', name: 'left right double arrow with stroke' },
    { char: '⇏', name: 'rightwards double arrow with stroke' },
    { char: '⇐', name: 'leftwards double arrow' },
    { char: '⇑', name: 'upwards double arrow' },
    { char: '⇒', name: 'rightwards double arrow' },
    { char: '⇓', name: 'downwards double arrow' },
    { char: '⇔', name: 'left right double arrow' },
    { char: '⇕', name: 'up down double arrow' },
    { char: '⇖', name: 'north west double arrow' },
    { char: '⇗', name: 'north east double arrow' },
    { char: '⇘', name: 'south east double arrow' },
    { char: '⇙', name: 'south west double arrow' },
    { char: '⇚', name: 'leftwards triple arrow' },
    { char: '⇛', name: 'rightwards triple arrow' },
    { char: '⇜', name: 'leftwards squiggle arrow' },
    { char: '⇝', name: 'rightwards squiggle arrow' },
    { char: '⇞', name: 'upwards arrow with double stroke' },
    { char: '⇟', name: 'downwards arrow with double stroke' },
    { char: '⇠', name: 'leftwards dashe arrow' },
    { char: '⇡', name: 'upwards dashed arrow' },
    { char: '⇢', name: 'rightwards dashed arrow' },
    { char: '⇣', name: 'downwards dashed arrow' },
    { char: '⇤', name: 'leftwards arrow to bar' },
    { char: '⇥', name: 'rightwards arrow to bar' },
    { char: '⇦', name: 'leftwards white arrow' },
    { char: '⇧', name: 'upwards white arrow' },
    { char: '⇨', name: 'rightwards white arrow' },
    { char: '⇩', name: 'downwards white arrow' },
    { char: '⇪', name: 'upwards white arrow from bar' },
    { char: '⇫', name: 'upwards white arrow on pedestal' },
    { char: '⇬', name: 'upwards white arrow on pedestal with horizontal bar' },
    { char: '⇭', name: 'upwards white arrow on pedestal with vertical bar' },
    { char: '⇮', name: 'upwards white double arrow' },
    { char: '⇯', name: 'upwards white double arrow on pedestal' },
    { char: '⇰', name: 'rightwards white arrow from wall' },
    { char: '⇱', name: 'north west arrow to corner' },
    { char: '⇲', name: 'south east arrow to corner' },
    { char: '⇳', name: 'up down white arrow' },
    { char: '⇴', name: 'right arrow with small circle' },
    { char: '⇵', name: 'downwards arrow leftwards of upwards arrow' },
    { char: '⇶', name: 'three rightwards arrows' },
    { char: '⇷', name: 'leftwards arrow with vertical stroke' },
    { char: '⇸', name: 'rightwards arrow with vertical stroke' },
    { char: '⇹', name: 'left right arrow with vertical stroke' },
    { char: '⇺', name: 'leftwards arrow with double vertical stroke' },
    { char: '⇻', name: 'rightwards arrow with double vertical stroke' },
    { char: '⇼', name: 'left right arrow with double vertical stroke' },
    { char: '⇽', name: 'leftwards open-headed arrow' },
    { char: '⇾', name: 'rightwards open-headed arrow' },
    { char: '⇿', name: 'left right open-headed arrow' },
    { char: '⟰', name: 'upwards quadruple arrow' },
    { char: '⟱', name: 'downwards quadruple arrow' },
    { char: '⟲', name: 'anticlockwise gapped circle arrow' },
    { char: '⟳', name: 'clockwise gapped circle arrow' },
    { char: '⟴', name: 'right arrow with circled plus' },
    { char: '⟵', name: 'long leftwards arrow' },
    { char: '⟶', name: 'long rightwards arrow' },
    { char: '⟷', name: 'long left right arrow' },
    { char: '⟸', name: 'long leftwards double arrow' },
    { char: '⟹', name: 'long rightwards double arrow' },
    { char: '⟺', name: 'long left right double arrow' },
    { char: '⟻', name: 'long leftwards arrow from bar' },
    { char: '⟼', name: 'long rightwards arrow from bar' },
    { char: '⟽', name: 'long leftwards double arrow from bar' },
    { char: '⟾', name: 'long rightwards double arrow from bar' },
    { char: '⟿', name: 'long rightwards squiggle arrow' },
    { char: '⤀', name: 'rightwards two-headed arrow with vertical stroke' },
    { char: '⤁', name: 'rightwards two-headed arrow with double vertical stroke' },
    { char: '⤂', name: 'leftwards double arrow with vertical stroke' },
    { char: '⤃', name: 'rightwards double arrow with vertical stroke' },
    { char: '⤄', name: 'left right double arrow with vertical stroke' },
    { char: '⤅', name: 'rightwards two-headed arrow from bar' },
    { char: '⤆', name: 'leftwards double arrow from bar' },
    { char: '⤇', name: 'rightwards double arrow from bar' },
    { char: '⤈', name: 'downwards arrow with horizontal stroke' },
    { char: '⤉', name: 'upwards arrow with horizontal stroke' },
    { char: '⤊', name: 'upwards triple arrow' },
    { char: '⤋', name: 'downwards triple arrow' },
    { char: '⤌', name: 'leftwards double dash arrow' },
    { char: '⤍', name: 'rightwards double dash arrow' },
    { char: '⤎', name: 'leftwards triple dash arrow' },
    { char: '⤏', name: 'rightwards triple dash arrow' },
    { char: '⤐', name: 'rightwards two-headed triple dash arrow' },
    { char: '⤑', name: 'rightwards arrow with dotted stem' },
    { char: '⤒', name: 'upwards arrow to bar' },
    { char: '⤓', name: 'downwards arrow to bar' },
    { char: '⤔', name: 'rightwards arrow with tail with vertical stroke' },
    { char: '⤕', name: 'rightwards arrow with tail with double vertical stroke' },
    { char: '⤖', name: 'rightwards two-headed arrow with tail' },
    { char: '⤗', name: 'rightwards two-headed arrow with tail with vertical stroke' },
    { char: '⤘', name: 'rightwards two-headed arrow with tail with double vertical stroke' },
    { char: '⤙', name: 'leftwards arrow-tail' },
    { char: '⤚', name: 'rightwards arrow-tail' },
    { char: '⤛', name: 'leftwards double arrow-tail' },
    { char: '⤜', name: 'rightwards double arrow-tail' },
    { char: '⤝', name: 'leftwards arrow to black diamond' },
    { char: '⤞', name: 'rightwards arrow to black diamond' },
    { char: '⤟', name: 'leftwards arrow from bar to black diamond' },
    { char: '⤠', name: 'rightwards arrow from bar to black diamond' },
    { char: '⤡', name: 'north west and south east arrow' },
    { char: '⤢', name: 'north east and south west arrow' },
    { char: '⤣', name: 'north west arrow with hook' },
    { char: '⤤', name: 'north east arrow with hook' },
    { char: '⤥', name: 'south east arrow with hook' },
    { char: '⤦', name: 'south west arrow with hook' },
    { char: '⤧', name: 'north west arrow and north east arrow' },
    { char: '⤨', name: 'north east arrow and south east arrow' },
    { char: '⤩', name: 'south east arrow and south west arrow' },
    { char: '⤪', name: 'south west arrow and north west arrow' },
    { char: '⤫', name: 'rising diagonal crossing falling diagonal' },
    { char: '⤬', name: 'falling diagonal crossing rising diagonal' },
    { char: '⤭', name: 'south east arrow crossing north east arrow' },
    { char: '⤮', name: 'north east arrow crossing south east arrow' },
    { char: '⤯', name: 'falling diagonal crossing north east arrow' },
    { char: '⤰', name: 'rising diagonal crossing south east arrow' },
    { char: '⤱', name: 'north east arrow crossing north west arrow' },
    { char: '⤲', name: 'north west arrow crossing north east arrow' },
    { char: '⤳', name: 'wave arrow pointing directly right' },
    { char: '⤴', name: 'arrow pointing rightwards then curving upwards' },
    { char: '⤵', name: 'arrow pointing rightwards then curving downwards' },
    { char: '⤶', name: 'arrow pointing downwards then curving leftwards' },
    { char: '⤷', name: 'arrow pointing downwards then curving rightwards' },
    { char: '⤸', name: 'right-side arc clockwise arrow' },
    { char: '⤹', name: 'left-side arc anticlockwise arrow' },
    { char: '⤺', name: 'top arc anticlockwise arrow' },
    { char: '⤻', name: 'bottom arc anticlockwise arrow' },
    { char: '⤼', name: 'top arc clockwise arrow with minus' },
    { char: '⤽', name: 'top arc anticlockwise arrow with plus' },
    { char: '⤾', name: 'lower right semicircular clockwise arrow' },
    { char: '⤿', name: 'lower left semicircular anticlockwise arrow' },
    { char: '⥀', name: 'anticlockwise closed circle arrow' },
    { char: '⥁', name: 'clockwise closed circle arrow' },
    { char: '⥂', name: 'rightwards arrow above short leftwards arrow' },
    { char: '⥃', name: 'leftwards arrow above short rightwards arrow' },
    { char: '⥄', name: 'short rightwards arrow above leftwards arrow' },
    { char: '⥅', name: 'rightwards arrow with plus below' },
    { char: '⥆', name: 'leftwards arrow with plus below' },
    { char: '⥇', name: 'rightwards arrow through x' },
    { char: '⥈', name: 'left right arrow through small circle' },
    { char: '⥉', name: 'upwards two-headed arrow from small circle' },
    { char: '⥊', name: 'left barb up right barb down harpoon' },
    { char: '⥋', name: 'left barb down right barb up harpoon' },
    { char: '⥌', name: 'up barb right down barb left harpoon' },
    { char: '⥍', name: 'up barb left down barb right harpoon' },
    { char: '⥎', name: 'left barb up right barb up harpoon' },
    { char: '⥏', name: 'up barb right down barb right harpoon' },
    { char: '⥐', name: 'left barb down right barb down harpoon' },
    { char: '⥑', name: 'up barb left down barb left harpoon' },
    { char: '⥒', name: 'leftwards harpoon with barb up to bar' },
    { char: '⥓', name: 'rightwards harpoon with barb up to bar' },
    { char: '⥔', name: 'upwards harpoon with barb right to bar' },
    { char: '⥕', name: 'downwards harpoon with barb right to bar' },
    { char: '⥖', name: 'leftwards harpoon with barb down to bar' },
    { char: '⥗', name: 'rightwards harpoon with barb down to bar' },
    { char: '⥘', name: 'upwards harpoon with barb left to bar' },
    { char: '⥙', name: 'downwards harpoon with barb left to bar' },
    { char: '⥚', name: 'leftwards harpoon with barb up from bar' },
    { char: '⥛', name: 'rightwards harpoon with barb up from bar' },
    { char: '⥜', name: 'upwards harpoon with barb right from bar' },
    { char: '⥝', name: 'downwards harpoon with barb right from bar' },
    { char: '⥞', name: 'leftwards harpoon with barb down from bar' },
    { char: '⥟', name: 'rightwards harpoon with barb down from bar' },
    { char: '⥠', name: 'upwards harpoon with barb left from bar' },
    { char: '⥡', name: 'downwards harpoon with barb left from bar' },
    { char: '⥢', name: 'leftwards harpoon with barb up above leftwards harpoon with barb down' },
    { char: '⥣', name: 'upwards harpoon with barb left beside upwards harpoon with barb right' },
    { char: '⥤', name: 'rightwards harpoon with barb up above rightwards harpoon with barb down' },
    { char: '⥥', name: 'downwards harpoon with barb left beside downwards harpoon with barb right' },
    { char: '⥦', name: 'leftwards harpoon with barb up above rightwards harpoon with barb up' },
    { char: '⥧', name: 'leftwards harpoon with barb down above rightwards harpoon with barb down' },
    { char: '⥨', name: 'rightwards harpoon with barb up above leftwards harpoon with barb up' },
    { char: '⥩', name: 'rightwards harpoon with barb down above leftwards harpoon with barb down' },
    { char: '⥪', name: 'leftwards harpoon with barb up above long dash' },
    { char: '⥫', name: 'leftwards harpoon with barb down below long dash' },
    { char: '⥬', name: 'rightwards harpoon with barb up above long dash' },
    { char: '⥭', name: 'rightwards harpoon with barb down below long dash' },
    { char: '⥮', name: 'upwards harpoon with barb left beside downwards harpoon with barb right' },
    { char: '⥯', name: 'downwards harpoon with barb left beside upwards harpoon with barb right' },
    { char: '⥰', name: 'right double arrow with rounded head' },
    { char: '⥱', name: 'equals sign above rightwards arrow' },
    { char: '⥲', name: 'tilde operator above rightwards arrow' },
    { char: '⥳', name: 'leftwards arrow above tilde operator' },
    { char: '⥴', name: 'rightwards arrow above tilde operator' },
    { char: '⥵', name: 'rightwards arrow above almost equal to' },
    { char: '⥶', name: 'less-than above leftwards arrow' },
    { char: '⥷', name: 'leftwards arrow through less-than' },
    { char: '⥸', name: 'greater-than above rightwards arrow' },
    { char: '⥹', name: 'subset above rightwards arrow' },
    { char: '⥺', name: 'leftwards arrow through subset' },
    { char: '⥻', name: 'superset above leftwards arrow' },
    { char: '⥼', name: 'left fish tail' },
    { char: '⥽', name: 'right fish tail' },
    { char: '⥾', name: 'up fish tail' },
    { char: '⥿', name: 'down fish tail' },
    { char: '🠀', name: 'leftwards arrow with small triangle arrowhead' },
    { char: '🠁', name: 'upwards arrow with small triangle arrowhead' },
    { char: '🠂', name: 'rightwards arrow with small triangle arrowhead' },
    { char: '🠃', name: 'downwards arrow with small triangle arrowhead' },
    { char: '🠄', name: 'leftwards arrow with medium triangle arrowhead' },
    { char: '🠅', name: 'upwards arrow with medium triangle arrowhead' },
    { char: '🠆', name: 'rightwards arrow with medium triangle arrowhead' },
    { char: '🠇', name: 'downwards arrow with medium triangle arrowhead' },
    { char: '🠈', name: 'leftwards arrow with large triangle arrowhead' },
    { char: '🠉', name: 'upwards arrow with large triangle arrowhead' },
    { char: '🠊', name: 'rightwards arrow with large triangle arrowhead' },
    { char: '🠋', name: 'downwards arrow with large triangle arrowhead' },
    { char: '🠐', name: 'leftwards arrow with small equilateral arrowhead' },
    { char: '🠑', name: 'upwards arrow with small equilateral arrowhead' },
    { char: '🠒', name: 'rightwards arrow with small equilateral arrowhead' },
    { char: '🠓', name: 'downwards arrow with small equilateral arrowhead' },
    { char: '🠔', name: 'leftwards arrow with equilateral arrowhead' },
    { char: '🠕', name: 'upwards arrow with equilateral arrowhead' },
    { char: '🠖', name: 'rightwards arrow with equilateral arrowhead' },
    { char: '🠗', name: 'downwards arrow with equilateral arrowhead' },
    { char: '🠘', name: 'heavy leftwards arrow with equilateral arrowhead' },
    { char: '🠙', name: 'heavy upwards arrow with equilateral arrowhead' },
    { char: '🠚', name: 'heavy rightwards arrow with equilateral arrowhead' },
    { char: '🠛', name: 'heavy downwards arrow with equilateral arrowhead' },
    { char: '🠜', name: 'heavy leftwards arrow with large equilateral arrowhead' },
    { char: '🠝', name: 'heavy upwards arrow with large equilateral arrowhead' },
    { char: '🠞', name: 'heavy rightwards arrow with large equilateral arrowhead' },
    { char: '🠟', name: 'heavy downwards arrow with large equilateral arrowhead' },
    { char: '🠠', name: 'leftwards triangle-headed arrow with narrow shaft' },
    { char: '🠡', name: 'upwards triangle-headed arrow with narrow shaft' },
    { char: '🠢', name: 'rightwards triangle-headed arrow with narrow shaft' },
    { char: '🠣', name: 'downwards triangle-headed arrow with narrow shaft' },
    { char: '🠤', name: 'leftwards triangle-headed arrow with medium shaft' },
    { char: '🠥', name: 'upwards triangle-headed arrow with medium shaft' },
    { char: '🠦', name: 'rightwards triangle-headed arrow with medium shaft' },
    { char: '🠧', name: 'downwards triangle-headed arrow with medium shaft' },
    { char: '🠨', name: 'leftwards triangle-headed arrow with bold shaft' },
    { char: '🠩', name: 'upwards triangle-headed arrow with bold shaft' },
    { char: '🠪', name: 'rightwards triangle-headed arrow with bold shaft' },
    { char: '🠫', name: 'downwards triangle-headed arrow with bold shaft' },
    { char: '🠬', name: 'leftwards triangle-headed arrow with heavy shaft' },
    { char: '🠭', name: 'upwards triangle-headed arrow with heavy shaft' },
    { char: '🠮', name: 'rightwards triangle-headed arrow with heavy shaft' },
    { char: '🠯', name: 'downwards triangle-headed arrow with very heavy shaft' },
    { char: '🠰', name: 'leftwards triangle-headed arrow with very heavy shaft' },
    { char: '🠱', name: 'upwards triangle-headed arrow with very heavy shaft' },
    { char: '🠲', name: 'rightwards triangle-headed arrow with very heavy shaft' },
    { char: '🠳', name: 'downwards triangle-headed arrow with very heavy shaft' },
    { char: '🠴', name: 'leftwards finger-post arrow' },
    { char: '🠵', name: 'upwards finger-post arrow' },
    { char: '🠶', name: 'rightwards finger-post arrow' },
    { char: '🠷', name: 'downwards finger-post arrow' },
    { char: '🠸', name: 'leftwards squared arrow' },
    { char: '🠹', name: 'upwards squared arrow' },
    { char: '🠺', name: 'rightwards squared arrow' },
    { char: '🠻', name: 'downwards squared arrow' },
    { char: '🠼', name: 'leftwards compressed arrow' },
    { char: '🠽', name: 'upwards compressed arrow' },
    { char: '🠾', name: 'rightwards compressed arrow' },
    { char: '🠿', name: 'downwards compressed arrow' },
    { char: '🡀', name: 'leftwards heavy compressed arrow' },
    { char: '🡁', name: 'upwards heavy compressed arrow' },
    { char: '🡂', name: 'rightwards heavy compressed arrow' },
    { char: '🡃', name: 'downwards heavy compressed arrow' },
    { char: '🡄', name: 'leftwards heavy arrow' },
    { char: '🡅', name: 'upwards heavy arrow' },
    { char: '🡆', name: 'rightwards heavy arrow' },
    { char: '🡇', name: 'downwards heavy arrow' },

    // Astrology
    { char: '☼', name: 'white sun with rays' },
    { char: '☽', name: 'first quarter moon' },
    { char: '☾', name: 'last quarter moon' },
    { char: '☿', name: 'mercury' },
    { char: '♀', name: 'venus' },
    { char: '♁', name: 'earth' },
    { char: '♂', name: 'mars' },
    { char: '♃', name: 'jupiter' },
    { char: '♄', name: 'saturn' },
    { char: '♅', name: 'uranus' },
    { char: '♆', name: 'neptune' },
    { char: '♇', name: 'pluto' },
    { char: '⛢', name: 'uranus symbol' },
    { char: '⚲', name: 'neuter' },
    { char: '⚳', name: 'ceres' },
    { char: '⚴', name: 'pallas' },
    { char: '⚵', name: 'juno' },
    { char: '⚶', name: 'vesta' },
    { char: '⚷', name: 'chiron' },
    { char: '⚸', name: 'black moon lilith' },
    { char: '⚹', name: 'sextile' },
    { char: '⚺', name: 'semisextile' },
    { char: '⚻', name: 'quincunx' },
    { char: '⚼', name: 'sesquiquadrate' },
    { char: '⚝', name: 'outlined white star' },
    { char: '⛤', name: 'pentagram' },
    { char: '♈', name: 'aries' },
    { char: '♉', name: 'taurus' },
    { char: '♊', name: 'gemini' },
    { char: '♋', name: 'cancer' },
    { char: '♌', name: 'leo' },
    { char: '♍', name: 'virgo' },
    { char: '♎', name: 'libra' },
    { char: '♏', name: 'scorpius' },
    { char: '♐', name: 'sagittarius' },
    { char: '♑', name: 'capricorn' },
    { char: '♒', name: 'aquarius' },
    { char: '♓', name: 'pisces' },
    { char: '⛎', name: 'ophiuchus' },
    { char: '⯊', name: 'top half black circle' },
    { char: '⯋', name: 'bottom half black circle' },
    { char: '⯌', name: 'light four pointed black cusp' },
    { char: '⯍', name: 'rotated light four pointed black cusp' },
    { char: '⯎', name: 'white four pointed cusp' },
    { char: '⯏', name: 'rotated white four pointed cusp' },
    { char: '⯐', name: 'square position indicator' },

    // Cards
    { char: '♠', name: 'black spade suit' },
    { char: '♡', name: 'white heart suit' },
    { char: '♢', name: 'white diamond suit' },
    { char: '♣', name: 'black club suit' },
    { char: '♤', name: 'white spade suit' },
    { char: '♥', name: 'black heart suit' },
    { char: '♦', name: 'black diamond suit' },
    { char: '🂠', name: 'playing card back' },
    { char: '🂡', name: 'playing card ace of spades' },
    { char: '🂢', name: 'playing card two of spades' },
    { char: '🂣', name: 'playing card three of spades' },
    { char: '🂤', name: 'playing card four of spades' },
    { char: '🂥', name: 'playing card five of spades' },
    { char: '🂦', name: 'playing card six of spades' },
    { char: '🂧', name: 'playing card seven of spades' },
    { char: '🂨', name: 'playing card eight of spades' },
    { char: '🂩', name: 'playing card nine of spades' },
    { char: '🂪', name: 'playing card ten of spades' },
    { char: '🂫', name: 'playing card jack of spades' },
    { char: '🂬', name: 'playing card knight of spades' },
    { char: '🂭', name: 'playing card queen of spades' },
    { char: '🂮', name: 'playing card king of spades' },
    { char: '🂱', name: 'playing card ace of hearts' },
    { char: '🂲', name: 'playing card two of hearts' },
    { char: '🂳', name: 'playing card three of hearts' },
    { char: '🂴', name: 'playing card four of hearts' },
    { char: '🂵', name: 'playing card five of hearts' },
    { char: '🂶', name: 'playing card six of hearts' },
    { char: '🂷', name: 'playing card seven of hearts' },
    { char: '🂸', name: 'playing card eight of hearts' },
    { char: '🂹', name: 'playing card nine of hearts' },
    { char: '🂺', name: 'playing card ten of hearts' },
    { char: '🂻', name: 'playing card jack of hearts' },
    { char: '🂼', name: 'playing card knight of hearts' },
    { char: '🂽', name: 'playing card queen of hearts' },
    { char: '🂾', name: 'playing card king of hearts' },
    { char: '🂿', name: 'playing card red joker' },
    { char: '🃁', name: 'playing card ace of diamonds' },
    { char: '🃂', name: 'playing card two of diamonds' },
    { char: '🃃', name: 'playing card three of diamonds' },
    { char: '🃄', name: 'playing card four of diamonds' },
    { char: '🃅', name: 'playing card five of diamonds' },
    { char: '🃆', name: 'playing card six of diamonds' },
    { char: '🃇', name: 'playing card seven of diamonds' },
    { char: '🃈', name: 'playing card eight of diamonds' },
    { char: '🃉', name: 'playing card nine of diamonds' },
    { char: '🃊', name: 'playing card ten of diamonds' },
    { char: '🃋', name: 'playing card jack of diamonds' },
    { char: '🃌', name: 'playing card knight of diamonds' },
    { char: '🃍', name: 'playing card queen of diamonds' },
    { char: '🃎', name: 'playing card king of diamonds' },
    { char: '🃏', name: 'playing card black joker' },
    { char: '🃑', name: 'playing card ace of clubs' },
    { char: '🃒', name: 'playing card two of clubs' },
    { char: '🃓', name: 'playing card three of clubs' },
    { char: '🃔', name: 'playing card four of clubs' },
    { char: '🃕', name: 'playing card five of clubs' },
    { char: '🃖', name: 'playing card six of clubs' },
    { char: '🃗', name: 'playing card seven of clubs' },
    { char: '🃘', name: 'playing card eight of clubs' },
    { char: '🃙', name: 'playing card nine of clubs' },
    { char: '🃚', name: 'playing card ten of clubs' },
    { char: '🃛', name: 'playing card jack of clubs' },
    { char: '🃜', name: 'playing card knight of clubs' },
    { char: '🃝', name: 'playing card queen of clubs' },
    { char: '🃞', name: 'playing card king of clubs' },
    { char: '🃟', name: 'playing card white joker' },
    { char: '🃠', name: 'playing card fool' },
    { char: '🃡', name: 'playing card trump-1' },
    { char: '🃢', name: 'playing card trump-2' },
    { char: '🃣', name: 'playing card trump-3' },
    { char: '🃤', name: 'playing card trump-4' },
    { char: '🃥', name: 'playing card trump-5' },
    { char: '🃦', name: 'playing card trump-6' },
    { char: '🃧', name: 'playing card trump-7' },
    { char: '🃨', name: 'playing card trump-8' },
    { char: '🃩', name: 'playing card trump-9' },
    { char: '🃪', name: 'playing card trump-10' },
    { char: '🃫', name: 'playing card trump-11' },
    { char: '🃬', name: 'playing card trump-12' },
    { char: '🃭', name: 'playing card trump-13' },
    { char: '🃮', name: 'playing card trump-14' },
    { char: '🃯', name: 'playing card trump-15' },
    { char: '🃰', name: 'playing card trump-16' },
    { char: '🃱', name: 'playing card trump-17' },
    { char: '🃲', name: 'playing card trump-18' },
    { char: '🃳', name: 'playing card trump-19' },
    { char: '🃴', name: 'playing card trump-20' },
    { char: '🃵', name: 'playing card trump-21' },

    // Chess
    { char: '♔', name: 'white chess king' },
    { char: '♕', name: 'white chess queen' },
    { char: '♖', name: 'white chess rook' },
    { char: '♗', name: 'white chess bishop' },
    { char: '♘', name: 'white chess knight' },
    { char: '♙', name: 'white chess pawn' },
    { char: '♚', name: 'black chess king' },
    { char: '♛', name: 'black chess queen' },
    { char: '♜', name: 'black chess rook' },
    { char: '♝', name: 'black chess bishop' },
    { char: '♞', name: 'black chess knight' },
    { char: '♟', name: 'black chess pawn' },
    { char: '⛉', name: 'turned white shogi piece' },
    { char: '⛊', name: 'turned black shogi piece' },
    { char: '☖', name: 'white shogi piece' },
    { char: '☗', name: 'black shogi piece' },

    // Currency
    { char: '₠', name: 'euro-currency sign' },
    { char: '₡', name: 'colon sign' },
    { char: '₢', name: 'cruzeiro sign' },
    { char: '₣', name: 'french franc sign' },
    { char: '₤', name: 'lira sign' },
    { char: '₥', name: 'mill sign' },
    { char: '₦', name: 'naira sign' },
    { char: '₧', name: 'peseta sign' },
    { char: '₨', name: 'rupee sign' },
    { char: '₩', name: 'won sign' },
    { char: '₪', name: 'new sheqel sign' },
    { char: '₫', name: 'dong sign' },
    { char: '€', name: 'euro sign' },
    { char: '₭', name: 'kip sign' },
    { char: '₮', name: 'tugrik sign' },
    { char: '₯', name: 'drachma sign' },
    { char: '₰', name: 'german penny sign' },
    { char: '₱', name: 'peso sign' },
    { char: '₲', name: 'guarani sign' },
    { char: '₳', name: 'austral sign' },
    { char: '₴', name: 'hryvnia sign' },
    { char: '₵', name: 'cedi sign' },
    { char: '₶', name: 'livre tournois sign' },
    { char: '₷', name: 'spesmilo sign' },
    { char: '₸', name: 'tenge sign' },
    { char: '₹', name: 'indian rupee sign' },
    { char: '₺', name: 'turkish lira sign' },
    { char: '₻', name: 'nordic mark sign' },
    { char: '₼', name: 'manat sign' },
    { char: '₽', name: 'ruble sign' },
    { char: '₾', name: 'lari sign' },
    { char: '₿', name: 'bitcoin sign' },

    // Dices and Tiles
    { char: '⚀', name: 'die face-1' },
    { char: '⚁', name: 'die face-2' },
    { char: '⚂', name: 'die face-3' },
    { char: '⚃', name: 'die face-4' },
    { char: '⚄', name: 'die face-5' },
    { char: '⚅', name: 'die face-6' },
    { char: '🀀', name: 'mahjong tile east wind' },
    { char: '🀁', name: 'mahjong tile south wind' },
    { char: '🀂', name: 'mahjong tile west wind' },
    { char: '🀃', name: 'mahjong tile north wind' },
    { char: '🀄', name: 'mahjong tile red dragon' },
    { char: '🀅', name: 'mahjong tile green dragon' },
    { char: '🀆', name: 'mahjong tile white dragon' },
    { char: '🀇', name: 'mahjong tile one of characters' },
    { char: '🀈', name: 'mahjong tile two of characters' },
    { char: '🀉', name: 'mahjong tile three of characters' },
    { char: '🀊', name: 'mahjong tile four of characters' },
    { char: '🀋', name: 'mahjong tile five of characters' },
    { char: '🀌', name: 'mahjong tile six of characters' },
    { char: '🀍', name: 'mahjong tile seven of characters' },
    { char: '🀎', name: 'mahjong tile eight of characters' },
    { char: '🀏', name: 'mahjong tile nine of characters' },
    { char: '🀐', name: 'mahjong tile one of bamboos' },
    { char: '🀑', name: 'mahjong tile two of bamboos' },
    { char: '🀒', name: 'mahjong tile three of bamboos' },
    { char: '🀓', name: 'mahjong tile four of bamboos' },
    { char: '🀔', name: 'mahjong tile five of bamboos' },
    { char: '🀕', name: 'mahjong tile six of bamboos' },
    { char: '🀖', name: 'mahjong tile seven of bamboos' },
    { char: '🀗', name: 'mahjong tile eight of bamboos' },
    { char: '🀘', name: 'mahjong tile nine of bamboos' },
    { char: '🀙', name: 'mahjong tile one of circles' },
    { char: '🀚', name: 'mahjong tile two of circles' },
    { char: '🀛', name: 'mahjong tile three of circles' },
    { char: '🀜', name: 'mahjong tile four of circles' },
    { char: '🀝', name: 'mahjong tile five of circles' },
    { char: '🀞', name: 'mahjong tile six of circles' },
    { char: '🀟', name: 'mahjong tile seven of circles' },
    { char: '🀠', name: 'mahjong tile eight of circles' },
    { char: '🀡', name: 'mahjong tile nine of circles' },
    { char: '🀢', name: 'mahjong tile plum' },
    { char: '🀣', name: 'mahjong tile orchid' },
    { char: '🀤', name: 'mahjong tile bamboo' },
    { char: '🀥', name: 'mahjong tile chrysanthemum' },
    { char: '🀦', name: 'mahjong tile spring' },
    { char: '🀧', name: 'mahjong tile summer' },
    { char: '🀨', name: 'mahjong tile autumn' },
    { char: '🀩', name: 'mahjong tile winter' },
    { char: '🀪', name: 'mahjong tile joker' },
    { char: '🀫', name: 'mahjong tile back' },
    { char: '🀰', name: 'domino tile horizontal back' },
    { char: '🀱', name: 'domino tile horizontal-00-00' },
    { char: '🀲', name: 'domino tile horizontal-00-01' },
    { char: '🀳', name: 'domino tile horizontal-00-02' },
    { char: '🀴', name: 'domino tile horizontal-00-03' },
    { char: '🀵', name: 'domino tile horizontal-00-04' },
    { char: '🀶', name: 'domino tile horizontal-00-05' },
    { char: '🀷', name: 'domino tile horizontal-00-06' },
    { char: '🀸', name: 'domino tile horizontal-01-01' },
    { char: '🀹', name: 'domino tile horizontal-01-02' },
    { char: '🀺', name: 'domino tile horizontal-01-03' },
    { char: '🀻', name: 'domino tile horizontal-01-04' },
    { char: '🀼', name: 'domino tile horizontal-01-05' },
    { char: '🀽', name: 'domino tile horizontal-01-06' },
    { char: '🀾', name: 'domino tile horizontal-02-02' },
    { char: '🀿', name: 'domino tile horizontal-02-03' },
    { char: '🁀', name: 'domino tile horizontal-02-04' },
    { char: '🁁', name: 'domino tile horizontal-02-05' },
    { char: '🁂', name: 'domino tile horizontal-02-06' },
    { char: '🁃', name: 'domino tile horizontal-03-03' },
    { char: '🁄', name: 'domino tile horizontal-03-04' },
    { char: '🁅', name: 'domino tile horizontal-03-05' },
    { char: '🁆', name: 'domino tile horizontal-03-06' },
    { char: '🁇', name: 'domino tile horizontal-04-04' },
    { char: '🁈', name: 'domino tile horizontal-04-05' },
    { char: '🁉', name: 'domino tile horizontal-04-06' },
    { char: '🁊', name: 'domino tile horizontal-05-05' },
    { char: '🁋', name: 'domino tile horizontal-05-06' },
    { char: '🁌', name: 'domino tile horizontal-06-06' },
    { char: '🁍', name: 'domino tile vertical back' },
    { char: '🁎', name: 'domino tile vertical-00-00' },
    { char: '🁏', name: 'domino tile vertical-00-01' },
    { char: '🁐', name: 'domino tile vertical-00-02' },
    { char: '🁑', name: 'domino tile vertical-00-03' },
    { char: '🁒', name: 'domino tile vertical-00-04' },
    { char: '🁓', name: 'domino tile vertical-00-05' },
    { char: '🁔', name: 'domino tile vertical-00-06' },
    { char: '🁕', name: 'domino tile vertical-01-01' },
    { char: '🁖', name: 'domino tile vertical-01-02' },
    { char: '🁗', name: 'domino tile vertical-01-03' },
    { char: '🁘', name: 'domino tile vertical-01-04' },
    { char: '🁙', name: 'domino tile vertical-01-05' },
    { char: '🁚', name: 'domino tile vertical-01-06' },
    { char: '🁛', name: 'domino tile vertical-02-02' },
    { char: '🁜', name: 'domino tile vertical-02-03' },
    { char: '🁝', name: 'domino tile vertical-02-04' },
    { char: '🁞', name: 'domino tile vertical-02-05' },
    { char: '🁟', name: 'domino tile vertical-02-06' },
    { char: '🁠', name: 'domino tile vertical-03-03' },
    { char: '🁡', name: 'domino tile vertical-03-04' },
    { char: '🁢', name: 'domino tile vertical-03-05' },
    { char: '🁣', name: 'domino tile vertical-03-06' },
    { char: '🁤', name: 'domino tile vertical-04-04' },
    { char: '🁥', name: 'domino tile vertical-04-05' },
    { char: '🁦', name: 'domino tile vertical-04-06' },
    { char: '🁧', name: 'domino tile vertical-05-05' },
    { char: '🁨', name: 'domino tile vertical-05-06' },
    { char: '🁩', name: 'domino tile vertical-06-06' },
    
    // Gender
    { char: '♀', name: 'female sign' },
    { char: '♂', name: 'male sign' },
    { char: '⚢', name: 'doubled female sign' },
    { char: '⚣', name: 'doubled male sign' },
    { char: '⚤', name: 'interlocked female and male sign' },
    { char: '⚥', name: 'male and female sign' },
    { char: '⚦', name: 'male with stroke sign' },
    { char: '⚧', name: 'transgender symbol male with stroke and male and female sign' },
    { char: '⚨', name: 'vertical male with stroke sign' },
    { char: '⚩', name: 'horizontal male with stroke sign' },
    { char: '⚭', name: 'marriage symbol' },
    { char: '⚮', name: 'divorce symbol' },
    { char: '⚯', name: 'unmarried partnership symbol' },

    // Music
    { char: '♩', name: 'quarter note' },
    { char: '♪', name: 'eighth note' },
    { char: '♫', name: 'beamed eighth notes' },
    { char: '♬', name: 'beamed sixteenth notes' },
    { char: '♭', name: 'music flat sign' },
    { char: '♮', name: 'music natural sign' },
    { char: '♯', name: 'music sharp sign' },
    { char: '𝄀', name: 'musical symbol single barline' },
    { char: '𝄁', name: 'musical symbol double barline' },
    { char: '𝄂', name: 'musical symbol final barline' },
    { char: '𝄃', name: 'musical symbol reverse final barline' },
    { char: '𝄄', name: 'musical symbol dashed barline' },
    { char: '𝄅', name: 'musical symbol short barline' },
    { char: '𝄆', name: 'musical symbol left repeat sign' },
    { char: '𝄇', name: 'musical symbol right repeat sign' },
    { char: '𝄈', name: 'musical symbol repeat dots' },
    { char: '𝄉', name: 'musical symbol dal segno' },
    { char: '𝄊', name: 'musical symbol da capo' },
    { char: '𝄋', name: 'musical symbol segno' },
    { char: '𝄌', name: 'musical symbol coda' },
    { char: '𝄍', name: 'musical symbol repeated figure-1' },
    { char: '𝄎', name: 'musical symbol repeated figure-2' },
    { char: '𝄏', name: 'musical symbol repeated figure-3' },
    { char: '𝄐', name: 'musical symbol fermata' },
    { char: '𝄑', name: 'musical symbol fermata below' },
    { char: '𝄒', name: 'musical symbol breath mark' },
    { char: '𝄓', name: 'musical symbol caesura' },
    { char: '𝄔', name: 'musical symbol brace' },
    { char: '𝄕', name: 'musical symbol bracket' },
    { char: '𝄖', name: 'musical symbol one-line staff' },
    { char: '𝄗', name: 'musical symbol two-line staff' },
    { char: '𝄘', name: 'musical symbol three-line staff' },
    { char: '𝄙', name: 'musical symbol four-line staff' },
    { char: '𝄚', name: 'musical symbol five-line staff' },
    { char: '𝄛', name: 'musical symbol six-line staff' },
    { char: '𝄜', name: 'musical symbol six-string fretboard' },
    { char: '𝄝', name: 'musical symbol four-string fretboard' },
    { char: '𝄞', name: 'musical symbol g clef' },
    { char: '𝄟', name: 'musical symbol g clef ottava alta' },
    { char: '𝄠', name: 'musical symbol g clef ottava bassa' },
    { char: '𝄡', name: 'musical symbol c clef' },
    { char: '𝄢', name: 'musical symbol f clef' },
    { char: '𝄣', name: 'musical symbol f clef ottava alta' },
    { char: '𝄤', name: 'musical symbol f clef ottava bassa' },
    { char: '𝄥', name: 'musical symbol drum clef-1' },
    { char: '𝄦', name: 'musical symbol drum clef-2' },
    { char: '𝄩', name: 'musical symbol multiple measure rest' },
    { char: '𝄪', name: 'musical symbol double sharp' },
    { char: '𝄫', name: 'musical symbol double flat' },
    { char: '𝄬', name: 'musical symbol flat up' },
    { char: '𝄭', name: 'musical symbol flat down' },
    { char: '𝄮', name: 'musical symbol natural up' },
    { char: '𝄯', name: 'musical symbol natural down' },
    { char: '𝄰', name: 'musical symbol sharp up' },
    { char: '𝄱', name: 'musical symbol sharp down' },
    { char: '𝄲', name: 'musical symbol quarter tone sharp' },
    { char: '𝄳', name: 'musical symbol quarter tone flat' },
    { char: '𝄴', name: 'musical symbol common time' },
    { char: '𝄵', name: 'musical symbol cut time' },
    { char: '𝄶', name: 'musical symbol ottava alta' },
    { char: '𝄷', name: 'musical symbol ottava bassa' },
    { char: '𝄸', name: 'musical symbol quindicesima alta' },
    { char: '𝄹', name: 'musical symbol quindicesima bassa' },
    { char: '𝄺', name: 'musical symbol multi rest' },
    { char: '𝄻', name: 'musical symbol whole rest' },
    { char: '𝄼', name: 'musical symbol half rest' },
    { char: '𝄽', name: 'musical symbol quarter rest' },
    { char: '𝄾', name: 'musical symbol eighth rest' },
    { char: '𝄿', name: 'musical symbol sixteenth rest' },
    { char: '𝅀', name: 'musical symbol thirty-second rest' },
    { char: '𝅁', name: 'musical symbol sixty-fourth rest' },
    { char: '𝅂', name: 'musical symbol one hundred twenty-eighth rest' },
    { char: '𝅃', name: 'musical symbol x notehead' },
    { char: '𝅄', name: 'musical symbol plus notehead' },
    { char: '𝅅', name: 'musical symbol circle x notehead' },
    { char: '𝅆', name: 'musical symbol square notehead white' },
    { char: '𝅇', name: 'musical symbol square notehead black' },
    { char: '𝅈', name: 'musical symbol triangle notehead up white' },
    { char: '𝅉', name: 'musical symbol triangle notehead up black' },
    { char: '𝅊', name: 'musical symbol triangle notehead left white' },
    { char: '𝅋', name: 'musical symbol triangle notehead left black' },
    { char: '𝅌', name: 'musical symbol triangle notehead right white' },
    { char: '𝅍', name: 'musical symbol triangle notehead right black' },
    { char: '𝅎', name: 'musical symbol triangle notehead down white' },
    { char: '𝅏', name: 'musical symbol triangle notehead down black' },
    { char: '𝅐', name: 'musical symbol triangle notehead up right white' },
    { char: '𝅑', name: 'musical symbol triangle notehead up right black' },
    { char: '𝅒', name: 'musical symbol moon notehead white' },
    { char: '𝅓', name: 'musical symbol moon notehead black' },
    { char: '𝅔', name: 'musical symbol triangle-round notehead down white' },
    { char: '𝅕', name: 'musical symbol triangle-round notehead down black' },
    { char: '𝅖', name: 'musical symbol parenthesis notehead' },
    { char: '𝅗', name: 'musical symbol void notehead' },
    { char: '𝅘', name: 'musical symbol notehead black' },
    { char: '𝅙', name: 'musical symbol null notehead' },
    { char: '𝅚', name: 'musical symbol cluster notehead white' },
    { char: '𝅛', name: 'musical symbol cluster notehead black' },
    { char: '𝅜', name: 'musical symbol breve' },
    { char: '𝅝', name: 'musical symbol whole note' },
    { char: '𝅗𝅥', name: 'musical symbol half note' },
    { char: '𝅘𝅥', name: 'musical symbol quarter note' },
    { char: '𝅘𝅥𝅮', name: 'musical symbol eighth note' },
    { char: '𝅘𝅥𝅯', name: 'musical symbol sixteenth note' },
    { char: '𝅘𝅥𝅰', name: 'musical symbol thirty-second note' },
    { char: '𝅘𝅥𝅱', name: 'musical symbol sixty-fourth note' },
    { char: '𝅘𝅥𝅲', name: 'musical symbol one hundred twenty-eighth note' },
    { char: '𝅘𝅥𝅥', name: 'musical symbol combining stem' },
    { char: '𝅘𝅥𝅦', name: 'musical symbol combining sprechgesang stem' },
    { char: '𝅘𝅧𝅥', name: 'musical symbol combining tremolo-1' },
    { char: '𝅘𝅨𝅥', name: 'musical symbol combining tremolo-2' },
    { char: '𝅘𝅩𝅥', name: 'musical symbol combining tremolo-3' },
    { char: '𝅪', name: 'musical symbol fingered tremolo-1' },
    { char: '𝅫', name: 'musical symbol fingered tremolo-2' },
    { char: '𝅬', name: 'musical symbol fingered tremolo-3' },
    { char: '𝅘𝅥𝅭', name: 'musical symbol combining augmentation dot' },
    { char: '𝅘𝅥𝅮', name: 'musical symbol combining flag-1' },
    { char: '𝅘𝅥𝅯', name: 'musical symbol combining flag-2' },
    { char: '𝅘𝅥𝅰', name: 'musical symbol combining flag-3' },
    { char: '𝅘𝅥𝅱', name: 'musical symbol combining flag-4' },
    { char: '𝅘𝅥𝅲', name: 'musical symbol combining flag-5' },
    { char: '𝅘𝅥𝅻', name: 'musical symbol combining accent' },
    { char: '𝅘𝅥𝅼', name: 'musical symbol combining staccato' },
    { char: '𝅘𝅥𝅽', name: 'musical symbol combining tenuto' },
    { char: '𝅘𝅥𝅾', name: 'musical symbol combining staccatissimo' },
    { char: '𝅘𝅥𝅿', name: 'musical symbol combining marcato' },
    { char: '𝅘𝅥𝆀', name: 'musical symbol combining marcato-staccato' },
    { char: '𝅘𝅥𝆁', name: 'musical symbol combining accent-staccato' },
    { char: '𝅘𝅥𝆂', name: 'musical symbol combining loure' },
    { char: '𝆃', name: 'musical symbol arpeggiato up' },
    { char: '𝆄', name: 'musical symbol arpeggiato down' },
    { char: '𝅘𝅥𝆅', name: 'musical symbol combining doit' },
    { char: '𝅘𝅥𝆆', name: 'musical symbol combining rip' },
    { char: '𝅘𝅥𝆇', name: 'musical symbol combining flip' },
    { char: '𝅘𝅥𝆈', name: 'musical symbol combining smear' },
    { char: '𝅘𝅥𝆉', name: 'musical symbol combining bend' },
    { char: '𝅘𝅥𝆊', name: 'musical symbol combining double tongue' },
    { char: '𝅘𝅥𝆋', name: 'musical symbol combining triple tongue' },
    { char: '𝆌', name: 'musical symbol rinforzando' },
    { char: '𝆍', name: 'musical symbol subito' },
    { char: '𝆎', name: 'musical symbol z' },
    { char: '𝆏', name: 'musical symbol piano' },
    { char: '𝆐', name: 'musical symbol mezzo' },
    { char: '𝆑', name: 'musical symbol forte' },
    { char: '𝆒', name: 'musical symbol crescendo' },
    { char: '𝆓', name: 'musical symbol decrescendo' },
    { char: '𝆔', name: 'musical symbol grace note slash' },
    { char: '𝆕', name: 'musical symbol grace note no slash' },
    { char: '𝆖', name: 'musical symbol tr' },
    { char: '𝆗', name: 'musical symbol turn' },
    { char: '𝆘', name: 'musical symbol inverted turn' },
    { char: '𝆙', name: 'musical symbol turn slash' },
    { char: '𝆚', name: 'musical symbol turn up' },
    { char: '𝆛', name: 'musical symbol ornament stroke-1' },
    { char: '𝆜', name: 'musical symbol ornament stroke-2' },
    { char: '𝆝', name: 'musical symbol ornament stroke-3' },
    { char: '𝆞', name: 'musical symbol ornament stroke-4' },
    { char: '𝆟', name: 'musical symbol ornament stroke-5' },
    { char: '𝆠', name: 'musical symbol ornament stroke-6' },
    { char: '𝆡', name: 'musical symbol ornament stroke-7' },
    { char: '𝆢', name: 'musical symbol ornament stroke-8' },
    { char: '𝆣', name: 'musical symbol ornament stroke-9' },
    { char: '𝆤', name: 'musical symbol ornament stroke-10' },
    { char: '𝆥', name: 'musical symbol ornament stroke-11' },
    { char: '𝆦', name: 'musical symbol hauptstimme' },
    { char: '𝆧', name: 'musical symbol nebenstimme' },
    { char: '𝆨', name: 'musical symbol end of stimme' },
    { char: '𝆩', name: 'musical symbol degree slash' },
    { char: '𝅘𝅥𝆪', name: 'musical symbol combining down bow' },
    { char: '𝅘𝅥𝆫', name: 'musical symbol combining up bow' },
    { char: '𝅘𝅥𝆬', name: 'musical symbol combining harmonic' },
    { char: '𝅘𝅥𝆭', name: 'musical symbol combining snap pizzicato' },
    { char: '𝆮', name: 'musical symbol pedal mark' },
    { char: '𝆯', name: 'musical symbol pedal up mark' },
    { char: '𝆰', name: 'musical symbol half pedal mark' },
    { char: '𝆱', name: 'musical symbol glissando up' },
    { char: '𝆲', name: 'musical symbol glissando down' },
    { char: '𝆳', name: 'musical symbol with fingernails' },
    { char: '𝆴', name: 'musical symbol damp' },
    { char: '𝆵', name: 'musical symbol damp all' },
    { char: '𝆶', name: 'musical symbol maxima' },
    { char: '𝆷', name: 'musical symbol longa' },
    { char: '𝆸', name: 'musical symbol brevis' },
    { char: '𝆹', name: 'musical symbol semibrevis white' },
    { char: '𝆺', name: 'musical symbol semibrevis black' },
    { char: '𝆹𝅥', name: 'musical symbol minima' },
    { char: '𝆺𝅥', name: 'musical symbol minima black' },
    { char: '𝆹𝅥𝅮', name: 'musical symbol semiminima white' },
    { char: '𝆺𝅥𝅮', name: 'musical symbol semiminima black' },
    { char: '𝆹𝅥𝅯', name: 'musical symbol fusa white' },
    { char: '𝆺𝅥𝅯', name: 'musical symbol fusa black' },
    { char: '𝇁', name: 'musical symbol longa perfecta rest' },
    { char: '𝇂', name: 'musical symbol longa imperfecta rest' },
    { char: '𝇃', name: 'musical symbol brevis rest' },
    { char: '𝇄', name: 'musical symbol semibrevis rest' },
    { char: '𝇅', name: 'musical symbol minima rest' },
    { char: '𝇆', name: 'musical symbol semiminima rest' },
    { char: '𝇇', name: 'musical symbol tempus perfectum cum prolatione perfecta' },
    { char: '𝇈', name: 'musical symbol tempus perfectum cum prolatione imperfecta' },
    { char: '𝇉', name: 'musical symbol tempus perfectum cum prolatione perfecta diminution-1' },
    { char: '𝇊', name: 'musical symbol tempus imperfectum cum prolatione perfecta' },
    { char: '𝇋', name: 'musical symbol tempus imperfectum cum prolatione imperfecta' },
    { char: '𝇌', name: 'musical symbol tempus imperfectum cum prolatione imperfecta diminution-1' },
    { char: '𝇍', name: 'musical symbol tempus imperfectum cum prolatione imperfecta diminution-2' },
    { char: '𝇎', name: 'musical symbol tempus imperfectum cum prolatione imperfecta diminution-3' },
    { char: '𝇏', name: 'musical symbol croix' },
    { char: '𝇐', name: 'musical symbol gregorian c clef' },
    { char: '𝇑', name: 'musical symbol gregorian f clef' },
    { char: '𝇒', name: 'musical symbol square b' },
    { char: '𝇓', name: 'musical symbol virga' },
    { char: '𝇔', name: 'musical symbol podatus' },
    { char: '𝇕', name: 'musical symbol clivis' },
    { char: '𝇖', name: 'musical symbol scandicus' },
    { char: '𝇗', name: 'musical symbol climacus' },
    { char: '𝇘', name: 'musical symbol torculus' },
    { char: '𝇙', name: 'musical symbol porrectus' },
    { char: '𝇚', name: 'musical symbol porrectus flexus' },
    { char: '𝇛', name: 'musical symbol scandicus flexus' },
    { char: '𝇜', name: 'musical symbol torculus resupinus' },
    { char: '𝇝', name: 'musical symbol pes subpunctis' },

    // Recycle
    { char: '☠', name: 'skull and crossbones' },
    { char: '☡', name: 'caution sign' },
    { char: '☢', name: 'radioactive sign' },
    { char: '☣', name: 'biohazard sign' },
    { char: '♲', name: 'universal recycling symbol' },
    { char: '♳', name: 'recycling symbol for type-1 plastics' },
    { char: '♴', name: 'recycling symbol for type-2 plastics' },
    { char: '♵', name: 'recycling symbol for type-3 plastics' },
    { char: '♶', name: 'recycling symbol for type-4 plastics' },
    { char: '♷', name: 'recycling symbol for type-5 plastics' },
    { char: '♸', name: 'recycling symbol for type-6 plastics' },
    { char: '♹', name: 'recycling symbol for type-7 plastics' },
    { char: '♺', name: 'recycling symbol for generic materials' },
    { char: '♻', name: 'black universal recycling symbol' },
    { char: '♼', name: 'recycled paper symbol' },
    { char: '♽', name: 'partially-recycled paper symbol' },
    { char: '♾', name: 'permanent paper sign' },

    // Religion
    { char: '☤', name: 'caduceus' },
    { char: '☥', name: 'ankh' },
    { char: '☦', name: 'orthodox cross christianity' },
    { char: '☧', name: 'chi rho' },
    { char: '☨', name: 'cross of lorraine' },
    { char: '☩', name: 'cross of jerusalem' },
    { char: '♰', name: 'west syriac cross' },
    { char: '♱', name: 'east syriac cross' },
    { char: '☪', name: 'star and crescent islam' },
    { char: '☫', name: 'farsi symbol' },
    { char: '☬', name: 'khanda' },
    { char: '☮', name: 'peace symbol' },
    { char: '☯', name: 'yin yang taoism' },
    { char: '☸', name: 'wheel of dharma buddhism' },
    { char: '⚛', name: 'humanist symbol atom' },
    { char: '⚰', name: 'coffin' },
    { char: '⚱', name: 'funeral urn' },
    { char: '☭', name: 'hammer and sickle' },
    { char: '⚒', name: 'hammer and pick' },
    { char: '⚔', name: 'crossed swords' },
    { char: '⛏', name: 'pick' },
    { char: '⛨', name: 'black cross on shield' },
    { char: '⛩', name: 'shinto shrine' },
    { char: '✙', name: 'outlined greek cross' },
    { char: '✚', name: 'heavy greek cross' },
    { char: '✛', name: 'open centre cross' },
    { char: '✜', name: 'heavy open centre cross' },
    { char: '✝', name: 'latin cross christianity' },
    { char: '✞', name: 'shadowed white latin cross' },
    { char: '✟', name: 'outlined latin cross' },
    { char: '✠', name: 'maltese cross' },
    { char: '✡', name: 'star of david judaism' },
    { char: '🔯', name: 'six pointed star with middle dot' },
    { char: '🕀', name: 'circled cross pommee' },
    { char: '🕁', name: 'cross pommee with half-circle below' },
    { char: '🕂', name: 'cross pommee' },
    { char: '🕆', name: 'white latin cross christianity' },
    { char: '🕇', name: 'heavy latin cross christianity' },
    { char: '🕉', name: 'om symbol hinduism' },
    { char: '🕊', name: 'dove of peace' },
    { char: '🕋', name: 'kaaba islam' },
    { char: '🕌', name: 'mosque islam' },
    { char: '🕍', name: 'synagogue judaism' },
    { char: '🕎', name: 'menorah judaism' },

    // Weather
    { char: '☀', name: 'black sun with rays' },
    { char: '☁', name: 'cloud' },
    { char: '☂', name: 'umbrella' },
    { char: '☃', name: 'snowman' },
    { char: '☄', name: 'comet' },
    { char: '★', name: 'black star' },
    { char: '☆', name: 'white star' },
    { char: '☇', name: 'lightning' },
    { char: '☈', name: 'thunderstorm' },
    { char: '☉', name: 'sun' },
    { char: '☔', name: 'umbrella with rain drops' },
    { char: '⛄', name: 'snowman without snow' },
    { char: '⛅', name: 'sun behind cloud' },
    { char: '⛆', name: 'rain' },
    { char: '⛇', name: 'black snowman' },
    { char: '⛈', name: 'thunder cloud and rain' },
];
