
export type SymbolInfo = {
    char: string;
    name: string;
};

export const emojiSymbols: SymbolInfo[] = [
    // Smileys & People
    { char: '😀', name: 'grinning face' },
    { char: '😁', name: 'grinning face with smiling eyes' },
    { char: '😂', name: 'face with tears of joy' },
    { char: '😃', name: 'smiling face with open mouth' },
    { char: '😄', name: 'smiling face with open mouth and smiling eyes' },
    { char: '😅', name: 'smiling face with open mouth and cold sweat' },
    { char: '😆', name: 'smiling face with open mouth and tightly-closed eyes' },
    { char: '😇', name: 'smiling face with halo' },
    { char: '😈', name: 'smiling face with horns' },
    { char: '😉', name: 'winking face' },
    { char: '😊', name: 'smiling face with smiling eyes' },
    { char: '😋', name: 'face savouring delicious food' },
    { char: '😌', name: 'relieved face' },
    { char: '😍', name: 'smiling face with heart-shaped eyes' },
    { char: '😎', name: 'smiling face with sunglasses' },
    { char: '😏', name: 'smirking face' },
    { char: '😐', name: 'neutral face' },
    { char: '😑', name: 'expressionless face' },
    { char: '😒', name: 'unamused face' },
    { char: '😓', name: 'face with cold sweat' },
    { char: '😔', name: 'pensive face' },
    { char: '😕', name: 'confused face' },
    { char: '😖', name: 'confounded face' },
    { char: '😗', name: 'kissing face' },
    { char: '😘', name: 'face throwing a kiss' },
    { char: '😙', name: 'kissing face with smiling eyes' },
    { char: '😚', name: 'kissing face with closed eyes' },
    { char: '😛', name: 'face with stuck-out tongue' },
    { char: '😜', name: 'face with stuck-out tongue and winking eye' },
    { char: '😝', name: 'face with stuck-out tongue and tightly-closed eyes' },
    { char: '😞', name: 'disappointed face' },
    { char: '😟', name: 'worried face' },
    { char: '😠', name: 'angry face' },
    { char: '😡', name: 'pouting face' },
    { char: '😢', name: 'crying face' },
    { char: '😣', name: 'persevering face' },
    { char: '😤', name: 'face with look of triumph' },
    { char: '😥', name: 'disappointed but relieved face' },
    { char: '😦', name: 'frowning face with open mouth' },
    { char: '😧', name: 'anguished face' },
    { char: '😨', name: 'fearful face' },
    { char: '😩', name: 'weary face' },
    { char: '😪', name: 'sleepy face' },
    { char: '😫', name: 'tired face' },
    { char: '😬', name: 'grimacing face' },
    { char: '😭', name: 'loudly crying face' },
    { char: '😮', name: 'face with open mouth' },
    { char: '😯', name: 'hushed face' },
    { char: '😰', name: 'face with open mouth and cold sweat' },
    { char: '😱', name: 'face screaming in fear' },
    { char: '😲', name: 'astonished face' },
    { char: '😳', name: 'flushed face' },
    { char: '😴', name: 'sleeping face' },
    { char: '😵', name: 'dizzy face' },
    { char: '😶', name: 'face without mouth' },
    { char: '😷', name: 'face with medical mask' },
    { char: '🙁', name: 'slightly frowning face' },
    { char: '🙂', name: 'slightly smiling face' },
    { char: '🙃', name: 'upside-down face' },
    { char: '🙄', name: 'face with rolling eyes' },
    { char: '🤐', name: 'zipper-mouth face' },
    { char: '🤑', name: 'money-mouth face' },
    { char: '🤒', name: 'face with thermometer' },
    { char: '🤓', name: 'nerd face' },
    { char: '🤔', name: 'thinking face' },
    { char: '🤕', name: 'face with head-bandage' },
    { char: '🤗', name: 'hugging face' },
    { char: '🤠', name: 'cowboy hat face' },
    { char: '🤢', name: 'nauseated face' },
    { char: '🤣', name: 'rolling on the floor laughing' },
    { char: '🤤', name: 'drooling face' },
    { char: '🤥', name: 'lying face' },
    { char: '🤧', name: 'sneezing face' },
    { char: '🤨', name: 'face with raised eyebrow' },
    { char: '🤩', name: 'star-struck' },
    { char: '🤪', name: 'zany face' },
    { char: '🤫', name: 'shushing face' },
    { char: '🤭', name: 'face with hand over mouth' },
    { char: '🤮', name: 'face vomiting' },
    { char: '🤯', name: 'exploding head' },
    { char: '🥰', name: 'smiling face with hearts' },
    { char: '🥱', name: 'yawning face' },
    { char: '🥳', name: 'partying face' },
    { char: '🥴', name: 'woozy face' },
    { char: '🥵', name: 'hot face' },
    { char: '🥶', name: 'cold face' },
    { char: '🥺', name: 'pleading face' },
    { char: '🧐', name: 'face with monocle' },
    { char: '😸', name: 'grinning cat face with smiling eyes' },
    { char: '😹', name: 'cat face with tears of joy' },
    { char: '😺', name: 'smiling cat face with open mouth' },
    { char: '😻', name: 'smiling cat face with heart-eyes' },
    { char: '😼', name: 'cat face with wry smile' },
    { char: '😽', name: 'kissing cat face' },
    { char: '😾', name: 'pouting cat face' },
    { char: '😿', name: 'crying cat face' },
    { char: '🙀', name: 'weary cat face' },
    { char: '🙈', name: 'see-no-evil monkey' },
    { char: '🙉', name: 'hear-no-evil monkey' },
    { char: '🙊', name: 'speak-no-evil monkey' },
    { char: '👿', name: 'angry face with horns' },
    { char: '💀', name: 'skull' },
    { char: '🤬', name: 'face with symbols on mouth' },
    { char: '✋', name: 'raised hand' },
    { char: '👋', name: 'waving hand' },
    { char: '🖐', name: 'hand with fingers splayed' },
    { char: '🖖', name: 'vulcan salute' },
    { char: '🤚', name: 'raised back of hand' },
    { char: '☝', name: 'index pointing up' },
    { char: '👆', name: 'backhand index pointing up' },
    { char: '👇', name: 'backhand index pointing down' },
    { char: '👈', name: 'backhand index pointing left' },
    { char: '👉', name: 'backhand index pointing right' },
    { char: '🖕', name: 'middle finger' },
    { char: '✊', name: 'raised fist' },
    { char: '👊', name: 'oncoming fist' },
    { char: '👍', name: 'thumbs up' },
    { char: '👎', name: 'thumbs down' },
    { char: '🤛', name: 'left-facing fist' },
    { char: '🤜', name: 'right-facing fist' },
    { char: '✌', name: 'victory hand' },
    { char: '👌', name: 'OK hand' },
    { char: '🤏', name: 'pinching hand' },
    { char: '🤘', name: 'sign of the horns' },
    { char: '🤙', name: 'call me hand' },
    { char: '🤞', name: 'crossed fingers' },
    { char: '🤟', name: 'love-you gesture' },
    { char: '✍', name: 'writing hand' },
    { char: '👏', name: 'clapping hands' },
    { char: '👐', name: 'open hands' },
    { char: '💅', name: 'nail polish' },
    { char: '🤝', name: 'handshake' },
    { char: '🤲', name: 'palms up together' },
    { char: '🤳', name: 'selfie' },
    { char: '👮', name: 'police officer' },
    { char: '👯', name: 'people with bunny ears' },
    { char: '👰', name: 'bride with veil' },
    { char: '👲', name: 'man with gua pi mao' },
    { char: '👳', name: 'man with turban' },
    { char: '👷', name: 'construction worker' },
    { char: '👸', name: 'princess' },
    { char: '🕴', name: 'man in suit levitating' },
    { char: '🕵', name: 'detective' },
    { char: '💁', name: 'information desk person' },
    { char: '💂', name: 'guard' },
    { char: '💃', name: 'woman dancing' },
    { char: '🤴', name: 'prince' },
    { char: '🤵', name: 'man in tuxedo' },
    { char: '👪', name: 'family' },
    { char: '👫', name: 'man and woman holding hands' },
    { char: '👬', name: 'two men holding hands' },
    { char: '👭', name: 'two women holding hands' },
    { char: '💏', name: 'kiss' },
    { char: '💑', name: 'couple with heart' },
    { char: '🤰', name: 'pregnant woman' },
    { char: '🤱', name: 'breast-feeding' },
    { char: '👤', name: 'bust in silhouette' },
    { char: '👥', name: 'busts in silhouette' },
    { char: '👦', name: 'boy' },
    { char: '👧', name: 'girl' },
    { char: '👨', name: 'man' },
    { char: '👩', name: 'woman' },
    { char: '👱', name: 'person with blond hair' },
    { char: '👴', name: 'old man' },
    { char: '👵', name: 'old woman' },
    { char: '👶', name: 'baby' },
    { char: '🕺', name: 'man dancing' },
    { char: '🧍', name: 'person standing' },
    { char: '🧎', name: 'person kneeling' },
    { char: '🧑', name: 'adult' },
    { char: '🧒', name: 'child' },
    { char: '🧓', name: 'older adult' },
    { char: '🧔', name: 'man with beard' },
    { char: '🧕', name: 'woman with headscarf' },
    { char: '🧖', name: 'person in steamy room' },
    { char: '🧗', name: 'person climbing' },
    { char: '🧘', name: 'person in lotus position' },
    { char: '🦰', name: 'red hair' },
    { char: '🦱', name: 'curly hair' },
    { char: '🦲', name: 'bald' },
    { char: '🦳', name: 'white hair' },
    { char: '💆', name: 'person getting massage' },
    { char: '💇', name: 'person getting haircut' },
    { char: '🙅', name: 'person gesturing NO' },
    { char: '🙆', name: 'person gesturing OK' },
    { char: '🙇', name: 'person bowing' },
    { char: '🙋', name: 'person raising hand' },
    { char: '🙌', name: 'raising hands' },
    { char: '🙍', name: 'person frowning' },
    { char: '🙎', name: 'person pouting' },
    { char: '🙏', name: 'folded hands' },
    { char: '🤦', name: 'face palm' },
    { char: '🤷', name: 'shrug' },
    { char: '🧏', name: 'deaf person' },
    { char: '💬', name: 'speech balloon' },
    { char: '💭', name: 'thought balloon' },
    { char: '🗨', name: 'left speech bubble' },
    { char: '🗩', name: 'right speech bubble' },
    { char: '🗪', name: 'two speech bubbles' },
    { char: '🗫', name: 'three speech bubbles' },
    { char: '🗬', name: 'left thought bubble' },
    { char: '🗭', name: 'right thought bubble' },
    { char: '🗮', name: 'left anger bubble' },
    { char: '🗯', name: 'right anger bubble' },
    { char: '🗰', name: 'mood bubble' },
    { char: '🗱', name: 'lightning mood bubble' },
    { char: '🗲', name: 'lightning mood' },
    { char: '🎅', name: 'Santa Claus' },
    { char: '👹', name: 'Japanese Ogre' },
    { char: '👺', name: 'Japanese Goblin' },
    { char: '👻', name: 'ghost' },
    { char: '👼', name: 'baby angel' },
    { char: '👽', name: 'alien' },
    { char: '👾', name: 'alien monster' },
    { char: '🤖', name: 'robot face' },
    { char: '🤡', name: 'clown face' },
    { char: '🤶', name: 'Mrs. Claus' },
    { char: '🦸', name: 'superhero' },
    { char: '🦹', name: 'supervillain' },
    { char: '🧙', name: 'mage' },
    { char: '🧚', name: 'fairy' },
    { char: '🧛', name: 'vampire' },
    { char: '🧜', name: 'merperson' },
    { char: '🧝', name: 'elf' },
    { char: '🧞', name: 'genie' },
    { char: '🧟', name: 'zombie' },
    { char: '👀', name: 'eyes' },
    { char: '👁', name: 'eye' },
    { char: '👂', name: 'ear' },
    { char: '👃', name: 'nose' },
    { char: '👄', name: 'mouth' },
    { char: '👅', name: 'tongue' },
    { char: '👣', name: 'footprints' },
    { char: '💪', name: 'flexed biceps' },
    { char: '🦴', name: 'bone' },
    { char: '🦵', name: 'leg' },
    { char: '🦶', name: 'foot' },
    { char: '🦷', name: 'tooth' },
    { char: '🦻', name: 'ear with hearing aid' },
    { char: '🦼', name: 'motorized wheelchair' },
    { char: '🦽', name: 'manual wheelchair' },
    { char: '🦾', name: 'mechanical arm' },
    { char: '🦿', name: 'mechanical leg' },
    { char: '🧠', name: 'brain' },
    { char: '🧡', name: 'orange heart' },
    { char: '💌', name: 'love letter' },
    { char: '💒', name: 'wedding' },
    { char: '💓', name: 'beating heart' },
    { char: '💔', name: 'broken heart' },
    { char: '💕', name: 'two hearts' },
    { char: '💖', name: 'sparkling heart' },
    { char: '💗', name: 'growing heart' },
    { char: '💘', name: 'heart with arrow' },
    { char: '💙', name: 'blue heart' },
    { char: '💚', name: 'green heart' },
    { char: '💛', name: 'yellow heart' },
    { char: '💜', name: 'purple heart' },
    { char: '💝', name: 'heart with ribbon' },
    { char: '💞', name: 'revolving hearts' },
    { char: '💟', name: 'heart decoration' },
    { char: '🖤', name: 'black heart' },
    { char: '🤍', name: 'white heart' },
    { char: '🤎', name: 'brown heart' },
    { char: '🩵', name: 'light blue heart' },
    { char: '🩶', name: 'grey heart' },
    { char: '🩷', name: 'pink heart' },
    { char: '💄', name: 'lipstick' },
    { char: '💅', name: 'nail polish' },
    { char: '💈', name: 'barber pole' },
    { char: '💉', name: 'syringe' },
    { char: '💊', name: 'pill' },
    { char: '💋', name: 'kiss mark' },
    { char: '💍', name: 'ring' },
    { char: '💎', name: 'gem stone' },
    { char: '💤', name: 'zzz' },
    { char: '💩', name: 'pile of poo' },
    { char: '💫', name: 'dizzy' },
    { char: '🩸', name: 'drop of blood' },
    { char: '🩹', name: 'adhesive bandage' },
    { char: '🩺', name: 'stethoscope' },
    { char: '🩻', name: 'x-ray' },
    { char: '🩼', name: 'crutch' },
    { char: '💺', name: 'seat' },
    { char: '💻', name: 'laptop' },
    { char: '💼', name: 'briefcase' },
    { char: '💽', name: 'minidisc' },
    { char: '💾', name: 'floppy disk' },
    { char: '💿', name: 'optical disk' },
    { char: '📀', name: 'dvd' },
    { char: '📁', name: 'file folder' },
    { char: '📂', name: 'open file folder' },
    { char: '📃', name: 'page with curl' },
    { char: '📄', name: 'page facing up' },
    { char: '📅', name: 'calendar' },
    { char: '📆', name: 'tear-off calendar' },
    { char: '📇', name: 'card index' },
    { char: '📈', name: 'chart increasing' },
    { char: '📉', name: 'chart decreasing' },
    { char: '📊', name: 'bar chart' },
    { char: '📋', name: 'clipboard' },
    { char: '📌', name: 'pushpin' },
    { char: '📍', name: 'round pushpin' },
    { char: '📎', name: 'paperclip' },
    { char: '📏', name: 'straight ruler' },
    { char: '📐', name: 'triangular ruler' },
    { char: '📑', name: 'bookmark tabs' },
    { char: '📒', name: 'ledger' },
    { char: '📓', name: 'notebook' },
    { char: '📔', name: 'notebook with decorative cover' },
    { char: '📕', name: 'closed book' },
    { char: '📖', name: 'open book' },
    { char: '📗', name: 'green book' },
    { char: '📘', name: 'blue book' },
    { char: '📙', name: 'orange book' },
    { char: '📚', name: 'books' },
    { char: '📛', name: 'name badge' },
    { char: '📜', name: 'scroll' },
    { char: '📝', name: 'memo' },
    { char: '📞', name: 'telephone receiver' },
    { char: '📟', name: 'pager' },
    { char: '📠', name: 'fax machine' },
    { char: '📡', name: 'satellite antenna' },
    { char: '📢', name: 'loudspeaker' },
    { char: '📣', name: 'megaphone' },
    { char: '📤', name: 'outbox tray' },
    { char: '📥', name: 'inbox tray' },
    { char: '📰', name: 'newspaper' },
    { char: '🔋', name: 'battery' },
    { char: '🔌', name: 'electric plug' },
    { char: '🖇', name: 'linked paperclips' },
    { char: '🖈', name: 'black pushpin' },
    { char: '🖉', name: 'lower left pencil' },
    { char: '🖊', name: 'lower left ballpoint pen' },
    { char: '🖋', name: 'lower left fountain pen' },
    { char: '🖌', name: 'lower left paintbrush' },
    { char: '🖍', name: 'lower left crayon' },
    { char: '📱', name: 'mobile phone' },
    { char: '📲', name: 'mobile phone with arrow' },
    { char: '📳', name: 'vibration mode' },
    { char: '📴', name: 'mobile phone off' },
    { char: '📵', name: 'no mobile phones' },
    { char: '📶', name: 'antenna bars' },
    { char: '🕻', name: 'left hand telephone receiver' },
    { char: '🕼', name: 'telephone receiver with page' },
    { char: '🕽', name: 'right hand telephone receiver' },
    { char: '🕾', name: 'white touchtone telephone' },
    { char: '🕿', name: 'black touchtone telephone' },
    { char: '🖀', name: 'telephone on modem' },
    { char: '🖁', name: 'clamshell mobile phone' },
    { char: '📦', name: 'package' },
    { char: '📧', name: 'e-mail' },
    { char: '📨', name: 'incoming envelope' },
    { char: '📩', name: 'envelope with arrow' },
    { char: '📪', name: 'closed mailbox with lowered flag' },
    { char: '📫', name: 'closed mailbox with raised flag' },
    { char: '📬', name: 'open mailbox with raised flag' },
    { char: '📭', name: 'open mailbox with lowered flag' },
    { char: '📮', name: 'postbox' },
    { char: '📯', name: 'postal horn' },
    { char: '🖂', name: 'black envelope' },
    { char: '🖃', name: 'stamped envelope' },
    { char: '🖄', name: 'envelope with lightning' },
    { char: '🖅', name: 'flying envelope' },
    { char: '🖆', name: 'pen over envelope' },
    { char: '🕐', name: 'one o’clock' },
    { char: '🕑', name: 'two o’clock' },
    { char: '🕒', name: 'three o’clock' },
    { char: '🕓', name: 'four o’clock' },
    { char: '🕔', name: 'five o’clock' },
    { char: '🕕', name: 'six o’clock' },
    { char: '🕖', name: 'seven o’clock' },
    { char: '🕗', name: 'eight o’clock' },
    { char: '🕘', name: 'nine o’clock' },
    { char: '🕙', name: 'ten o’clock' },
    { char: '🕚', name: 'eleven o’clock' },
    { char: '🕛', name: 'twelve o’clock' },
    { char: '🕜', name: 'one-thirty' },
    { char: '🕝', name: 'two-thirty' },
    { char: '🕞', name: 'three-thirty' },
    { char: '🕟', name: 'four-thirty' },
    { char: '🕠', name: 'five-thirty' },
    { char: '🕡', name: 'six-thirty' },
    { char: '🕢', name: 'seven-thirty' },
    { char: '🕣', name: 'eight-thirty' },
    { char: '🕤', name: 'nine-thirty' },
    { char: '🕥', name: 'ten-thirty' },
    { char: '🕦', name: 'eleven-thirty' },
    { char: '🕧', name: 'twelve-thirty' },
    { char: '🖥', name: 'desktop computer' },
    { char: '🖨', name: 'printer' },
    { char: '🖱', name: 'computer mouse' },
    { char: '🖲', name: 'trackball' },
    { char: '🖼', name: 'framed picture' },
    { char: '🗂', name: 'card index dividers' },
    { char: '🗃', name: 'card file box' },
    { char: '🗄', name: 'file cabinet' },
    { char: '🗑', name: 'wastebasket' },
    { char: '🗒', name: 'spiral notepad' },
    { char: '🗓', name: 'spiral calendar' },
    { char: '🗜', name: 'clamp' },
    { char: '🗝', name: 'old key' },
    { char: '🗞', name: 'rolled-up newspaper' },
    { char: '🗡', name: 'dagger' },
    { char: '🗣', name: 'speaking head' },
    { char: '🗳', name: 'ballot box with ballot' },
    { char: '⛲', name: 'fountain' },
    { char: '⛳', name: 'flag in hole' },
    { char: '⛺', name: 'tent' },
    { char: '⛽', name: 'fuel pump' },
    { char: '🌋', name: 'volcano' },
    { char: '🗺', name: 'world map' },
    { char: '🗻', name: 'mount fuji' },
    { char: '🗼', name: 'tokyo tower' },
    { char: '🗽', name: 'statue of liberty' },
    { char: '🗾', name: 'map of japan' },
    { char: '🗿', name: 'moai' },
    { char: '⛪', name: 'church' },
    { char: '🏠', name: 'house' },
    { char: '🏡', name: 'house with garden' },
    { char: '🏢', name: 'office building' },
    { char: '🏣', name: 'japanese post office' },
    { char: '🏤', name: 'post office' },
    { char: '🏥', name: 'hospital' },
    { char: '🏦', name: 'bank' },
    { char: '🏧', name: 'atm sign' },
    { char: '🏨', name: 'hotel' },
    { char: '🏩', name: 'love hotel' },
    { char: '🏪', name: 'convenience store' },
    { char: '🏫', name: 'school' },
    { char: '🏬', name: 'department store' },
    { char: '🏭', name: 'factory' },
    { char: '🏮', name: 'red paper lantern' },
    { char: '🏯', name: 'japanese castle' },
    { char: '🏰', name: 'castle' },
    { char: '🛕', name: 'hindu temple' },
    { char: '🏔', name: 'snow-capped mountain' },
    { char: '🏕', name: 'camping' },
    { char: '🏖', name: 'beach with umbrella' },
    { char: '🏗', name: 'building construction' },
    { char: '🏘', name: 'houses' },
    { char: '🏙', name: 'cityscape' },
    { char: '🏚', name: 'derelict house' },
    { char: '🏛', name: 'classical building' },
    { char: '🏜', name: 'desert' },
    { char: '🏝', name: 'desert island' },
    { char: '🏞', name: 'national park' },
    { char: '🏟', name: 'stadium' },
    { char: '🏍', name: 'motorcycle' },
    { char: '🏎', name: 'racing car' },
    { char: '🚀', name: 'rocket' },
    { char: '🚁', name: 'helicopter' },
    { char: '🚂', name: 'locomotive' },
    { char: '🚃', name: 'railway car' },
    { char: '🚄', name: 'high-speed train' },
    { char: '🚅', name: 'bullet train' },
    { char: '🚆', name: 'train' },
    { char: '🚇', name: 'metro' },
    { char: '🚈', name: 'light rail' },
    { char: '🚉', name: 'station' },
    { char: '🚊', name: 'tram' },
    { char: '🚋', name: 'tram car' },
    { char: '🚌', name: 'bus' },
    { char: '🚍', name: 'oncoming bus' },
    { char: '🚎', name: 'trolleybus' },
    { char: '🚏', name: 'bus stop' },
    { char: '🚐', name: 'minibus' },
    { char: '🚑', name: 'ambulance' },
    { char: '🚒', name: 'fire engine' },
    { char: '🚓', name: 'police car' },
    { char: '🚔', name: 'oncoming police car' },
    { char: '🚕', name: 'taxi' },
    { char: '🚖', name: 'oncoming taxi' },
    { char: '🚗', name: 'automobile' },
    { char: '🚘', name: 'oncoming automobile' },
    { char: '🚙', name: 'recreational vehicle' },
    { char: '🚚', name: 'delivery truck' },
    { char: '🚛', name: 'articulated lorry' },
    { char: '🚜', name: 'tractor' },
    { char: '🚝', name: 'monorail' },
    { char: '🚞', name: 'mountain railway' },
    { char: '🚟', name: 'suspension railway' },
    { char: '🚠', name: 'mountain cableway' },
    { char: '🚡', name: 'aerial tramway' },
    { char: '🚢', name: 'ship' },
    { char: '🚣', name: 'person rowing boat' },
    { char: '🚤', name: 'speedboat' },
    { char: '🛴', name: 'kick scooter' },
    { char: '🛹', name: 'skateboard' },
    { char: '🛺', name: 'auto rickshaw' },
    { char: '⛔', name: 'no entry' },
    { char: '🚥', name: 'horizontal traffic light' },
    { char: '🚦', name: 'vertical traffic light' },
    { char: '🚧', name: 'construction' },
    { char: '🚨', name: 'police car light' },
    { char: '🚩', name: 'triangular flag' },
    { char: '🚪', name: 'door' },
    { char: '🚫', name: 'prohibited' },
    { char: '🚬', name: 'cigarette' },
    { char: '🚭', name: 'no smoking' },
    { char: '🚮', name: 'litter in bin sign' },
    { char: '🚯', name: 'no littering' },
    { char: '🚰', name: 'potable water' },
    { char: '🚱', name: 'non-potable water' },
    { char: '🚲', name: 'bicycle' },
    { char: '🚳', name: 'no bicycles' },
    { char: '🚴', name: 'person biking' },
    { char: '🚵', name: 'person mountain biking' },
    { char: '🚶', name: 'person walking' },
    { char: '🚷', name: 'no pedestrians' },
    { char: '🚸', name: 'children crossing' },
    { char: '🚹', name: 'men’s room' },
    { char: '🚺', name: 'women’s room' },
    { char: '🚻', name: 'restroom' },
    { char: '🚼', name: 'baby symbol' },
    { char: '🚽', name: 'toilet' },
    { char: '🚾', name: 'water closet' },
    { char: '🚿', name: 'shower' },
    { char: '🛀', name: 'person taking bath' },
    { char: '🛁', name: 'bathtub' },
    { char: '🛂', name: 'passport control' },
    { char: '🛃', name: 'customs' },
    { char: '🛄', name: 'baggage claim' },
    { char: '🛅', name: 'left luggage' },
    { char: '🛆', name: 'triangle with rounded corners' },
    { char: '🛇', name: 'prohibited sign' },
    { char: '🛈', name: 'information' },
    { char: '🛉', name: 'boys symbol' },
    { char: '🛊', name: 'girls symbol' },
    { char: '🛋', name: 'couch and lamp' },
    { char: '🛌', name: 'person in bed' },
    { char: '🛍', name: 'shopping bags' },
    { char: '🛎', name: 'bellhop bell' },
    { char: '🛏', name: 'bed' },
    { char: '🛐', name: 'place of worship' },
    { char: '🛑', name: 'stop sign' },
    { char: '🛒', name: 'shopping cart' },
    { char: '🛓', name: 'stupid' },
    { char: '🛔', name: 'coffin' },
    { char: '🛖', name: 'hut' },
    { char: '🛗', name: 'elevator' },
    { char: '🛘', name: 'playground slide' },
    { char: '🛙', name: 'wheel' },
    { char: '🛚', name: 'bus stop sign' },
    { char: '🛛', name: 'wheel' },
    { char: '🛜', name: 'wireless' },
    { char: '🛝', name: 'slide' },
    { char: '🛞', name: 'wheel' },
    { char: '🛟', name: 'ring buoy' },
    { char: '🛠', name: 'hammer and wrench' },
    { char: '🛡', name: 'shield' },
    { char: '🛢', name: 'oil drum' },
    { char: '🛣', name: 'motorway' },
    { char: '🛤', name: 'railway track' },
    { char: '🛥', name: 'motor boat' },
    { char: '🛦', name: 'small airplane' },
    { char: '🛧', name: 'airplane' },
    { char: '🛨', name: 'airplane departure' },
    { char: '🛩', name: 'airplane arrival' },
    { char: '🛪', name: 'airplane' },
    { char: '🛫', name: 'airplane departure' },
    { char: '🛬', name: 'airplane arrival' },
    { char: '🛭', name: 'airplane' },
    { char: '🛮', name: 'airplane' },
    { char: '🛯', name: 'airplane' },
    { char: '🛰', name: 'satellite' },
    { char: '🛱', name: 'oncoming fire engine' },
    { char: '🛲', name: 'oncoming police car' },
    { char: '🛳', name: 'passenger ship' },
    { char: '🛴', name: 'scooter' },
    { char: '🛵', name: 'motor scooter' },
    { char: '🛶', name: 'canoe' },
    { char: '🛷', name: 'sled' },
    { char: '🛸', name: 'flying saucer' },
    { char: '🛺', name: 'auto rickshaw' },
    { char: '🛻', name: 'pickup truck' },
    { char: '🛼', name: 'roller skate' },
    { char: '🐀', name: 'rat' },
    { char: '🐁', name: 'mouse' },
    { char: '🐂', name: 'ox' },
    { char: '🐃', name: 'water buffalo' },
    { char: '🐄', name: 'cow' },
    { char: '🐅', name: 'tiger' },
    { char: '🐆', name: 'leopard' },
    { char: '🐇', name: 'rabbit' },
    { char: '🐈', name: 'cat' },
    { char: '🐉', name: 'dragon' },
    { char: '🐊', name: 'crocodile' },
    { char: '🐋', name: 'whale' },
    { char: '🐌', name: 'snail' },
    { char: '🐍', name: 'snake' },
    { char: '🐎', name: 'horse' },
    { char: '🐏', name: 'ram' },
    { char: '🐐', name: 'goat' },
    { char: '🐑', name: 'ewe' },
    { char: '🐒', name: 'monkey' },
    { char: '🐓', name: 'rooster' },
    { char: '🐔', name: 'chicken' },
    { char: '🐕', name: 'dog' },
    { char: '🐖', name: 'pig' },
    { char: '🐗', name: 'boar' },
    { char: '🐘', name: 'elephant' },
    { char: '🐙', name: 'octopus' },
    { char: '🐚', name: 'spiral shell' },
    { char: '🐛', name: 'bug' },
    { char: '🐜', name: 'ant' },
    { char: '🐝', name: 'honeybee' },
    { char: '🐞', name: 'lady beetle' },
    { char: '🐟', name: 'fish' },
    { char: '🐠', name: 'tropical fish' },
    { char: '🐡', name: 'blowfish' },
    { char: '🐢', name: 'turtle' },
    { char: '🐣', name: 'hatching chick' },
    { char: '🐤', name: 'baby chick' },
    { char: '🐥', name: 'front-facing baby chick' },
    { char: '🐦', name: 'bird' },
    { char: '🐧', name: 'penguin' },
    { char: '🐨', name: 'koala' },
    { char: '🐩', name: 'poodle' },
    { char: '🐪', name: 'dromedary' },
    { char: '🐫', name: 'two-hump camel' },
    { char: '🐬', name: 'dolphin' },
    { char: '🐭', name: 'mouse face' },
    { char: '🐮', name: 'cow face' },
    { char: '🐯', name: 'tiger face' },
    { char: '🐰', name: 'rabbit face' },
    { char: '🐱', name: 'cat face' },
    { char: '🐲', name: 'dragon face' },
    { char: '🐳', name: 'spouting whale' },
    { char: '🐴', name: 'horse face' },
    { char: '🐵', name: 'monkey face' },
    { char: '🐶', name: 'dog face' },
    { char: '🐷', name: 'pig face' },
    { char: '🐸', name: 'frog face' },
    { char: '🐹', name: 'hamster face' },
    { char: '🐺', name: 'wolf face' },
    { char: '🐻', name: 'bear face' },
    { char: '🐼', name: 'panda face' },
    { char: '🐽', name: 'pig nose' },
    { char: '🐾', name: 'paw prints' },
    { char: '🐿', name: 'chipmunk' },
    { char: '🕷', name: 'spider' },
    { char: '🕸', name: 'spider web' },
    { char: '🦀', name: 'crab' },
    { char: '🦁', name: 'lion face' },
    { char: '🦂', name: 'scorpion' },
    { char: '🦃', name: 'turkey' },
    { char: '🦄', name: 'unicorn face' },
    { char: '🦅', name: 'eagle' },
    { char: '🦆', name: 'duck' },
    { char: '🦇', name: 'bat' },
    { char: '🦈', name: 'shark' },
    { char: '🦉', name: 'owl' },
    { char: '🦊', name: 'fox face' },
    { char: '🦋', name: 'butterfly' },
    { char: '🦌', name: 'deer' },
    { char: '🦍', name: 'gorilla' },
    { char: '🦎', name: 'lizard' },
    { char: '🦏', name: 'rhinoceros' },
    { char: '🦐', name: 'shrimp' },
    { char: '🦑', name: 'squid' },
    { char: '🦒', name: 'giraffe face' },
    { char: '🦓', name: 'zebra face' },
    { char: '🦔', name: 'hedgehog' },
    { char: '🦕', name: 'sauropod' },
    { char: '🦖', name: 'T-Rex' },
    { char: '🦗', name: 'cricket' },
    { char: '🦘', name: 'kangaroo' },
    { char: '🦙', name: 'llama' },
    { char: '🦚', name: 'peacock' },
    { char: '🦛', name: 'hippopotamus' },
    { char: '🦜', name: 'parrot' },
    { char: '🦝', name: 'raccoon' },
    { char: '🦞', name: 'lobster' },
    { char: '🦟', name: 'mosquito' },
    { char: '🦠', name: 'microbe' },
    { char: '🦡', name: 'badger' },
    { char: '🦢', name: 'swan' },
    { char: '🦣', name: 'mammoth' },
    { char: '🦤', name: 'dodo' },
    { char: '🦥', name: 'sloth' },
    { char: '🦦', name: 'otter' },
    { char: '🦧', name: 'orangutan' },
    { char: '🦨', name: 'skunk' },
    { char: '🦩', name: 'flamingo' },
    { char: '🦪', name: 'oyster' },
    { char: '🦫', name: 'beaver' },
    { char: '🦬', name: 'bison' },
    { char: '🦭', name: 'seal' },
    { char: '🦮', name: 'guide dog' },
    { char: '🦯', name: 'probing cane' },
    { char: '☕', name: 'hot beverage' },
    { char: '🍵', name: 'teacup without handle' },
    { char: '🍶', name: 'sake' },
    { char: '🍷', name: 'wine glass' },
    { char: '🍸', name: 'cocktail glass' },
    { char: '🍹', name: 'tropical drink' },
    { char: '🍺', name: 'beer mug' },
    { char: '🍻', name: 'clinking beer mugs' },
    { char: '🍼', name: 'baby bottle' },
    { char: '🍾', name: 'bottle with popping cork' },
    { char: '🏺', name: 'amphora' },
    { char: '🥂', name: 'clinking glasses' },
    { char: '🥃', name: 'tumbler glass' },
    { char: '🥛', name: 'glass of milk' },
    { char: '🥤', name: 'cup with straw' },
    { char: '🧃', name: 'beverage box' },
    { char: '🧉', name: 'mate' },
    { char: '🧊', name: 'ice' },
    { char: '🌭', name: 'hot dog' },
    { char: '🌮', name: 'taco' },
    { char: '🌯', name: 'burrito' },
    { char: '🍔', name: 'hamburger' },
    { char: '🍕', name: 'pizza' },
    { char: '🍖', name: 'meat on bone' },
    { char: '🍗', name: 'poultry leg' },
    { char: '🍘', name: 'rice cracker' },
    { char: '🍙', name: 'rice ball' },
    { char: '🍚', name: 'cooked rice' },
    { char: '🍛', name: 'curry rice' },
    { char: '🍜', name: 'steaming bowl' },
    { char: '🍝', name: 'spaghetti' },
    { char: '🍞', name: 'bread' },
    { char: '🍟', name: 'french fries' },
    { char: '🍠', name: 'roasted sweet potato' },
    { char: '🍡', name: 'dango' },
    { char: '🍢', name: 'oden' },
    { char: '🍣', name: 'sushi' },
    { char: '🍤', name: 'fried shrimp' },
    { char: '🍥', name: 'fish cake with swirl' },
    { char: '🍦', name: 'soft ice cream' },
    { char: '🍧', name: 'shaved ice' },
    { char: '🍨', name: 'ice cream' },
    { char: '🍩', name: 'doughnut' },
    { char: '🍪', name: 'cookie' },
    { char: '🍫', name: 'chocolate bar' },
    { char: '🍬', name: 'candy' },
    { char: '🍭', name: 'lollipop' },
    { char: '🍮', name: 'custard' },
    { char: '🍯', name: 'honey pot' },
    { char: '🍰', name: 'shortcake' },
    { char: '🍱', name: 'bento box' },
    { char: '🍲', name: 'pot of food' },
    { char: '🍳', name: 'cooking' },
    { char: '🍿', name: 'popcorn' },
    { char: '🥐', name: 'croissant' },
    { char: '🥓', name: 'bacon' },
    { char: '🥖', name: 'baguette bread' },
    { char: '🥗', name: 'green salad' },
    { char: '🥘', name: 'shallow pan of food' },
    { char: '🥙', name: 'stuffed flatbread' },
    { char: '🥚', name: 'egg' },
    { char: '🥜', name: 'peanuts' },
    { char: '🥞', name: 'pancakes' },
    { char: '🥟', name: 'dumpling' },
    { char: '🥠', name: 'fortune cookie' },
    { char: '🥡', name: 'takeout box' },
    { char: '🥣', name: 'bowl with spoon' },
    { char: '🥧', name: 'pie' },
    { char: '🥨', name: 'pretzel' },
    { char: '🥩', name: 'cut of meat' },
    { char: '🥪', name: 'sandwich' },
    { char: '🥫', name: 'canned food' },
    { char: '🥮', name: 'moon cake' },
    { char: '🥯', name: 'bagel' },
    { char: '🧀', name: 'cheese wedge' },
    { char: '🧁', name: 'cupcake' },
    { char: '🧆', name: 'falafel' },
    { char: '🧇', name: 'waffle' },
    { char: '🧈', name: 'butter' },
    { char: '🌽', name: 'ear of corn' },
    { char: '🌾', name: 'ear of rice' },
    { char: '🍄', name: 'mushroom' },
    { char: '🍅', name: 'tomato' },
    { char: '🍆', name: 'eggplant' },
    { char: '🥑', name: 'avocado' },
    { char: '🥒', name: 'cucumber' },
    { char: '🥔', name: 'potato' },
    { char: '🥕', name: 'carrot' },
    { char: '🥥', name: 'coconut' },
    { char: '🥦', name: 'broccoli' },
    { char: '🥬', name: 'leafy green' },
    { char: '🧄', name: 'garlic' },
    { char: '🧅', name: 'onion' },
    { char: '🍴', name: 'fork and knife' },
    { char: '🍽', name: 'fork and knife with plate' },
    { char: '🔪', name: 'kitchen knife' },
    { char: '🥄', name: 'spoon' },
    { char: '🥢', name: 'chopsticks' },
    { char: '🧂', name: 'salt' },
    { char: '🌰', name: 'chestnut' },
    { char: '🌱', name: 'seedling' },
    { char: '🌲', name: 'evergreen tree' },
    { char: '🌳', name: 'deciduous tree' },
    { char: '🌴', name: 'palm tree' },
    { char: '🌵', name: 'cactus' },
    { char: '🌶', name: 'hot pepper' },
    { char: '🌷', name: 'tulip' },
    { char: '🌸', name: 'cherry blossom' },
    { char: '🌹', name: 'rose' },
    { char: '🌺', name: 'hibiscus' },
    { char: '🌻', name: 'sunflower' },
    { char: '🌼', name: 'blossom' },
    { char: '🌿', name: 'herb' },
    { char: '🍀', name: 'four leaf clover' },
    { char: '🍁', name: 'maple leaf' },
    { char: '🍂', name: 'fallen leaf' },
    { char: '🍃', name: 'leaf fluttering in wind' },
    { char: '🍇', name: 'grapes' },
    { char: '🍈', name: 'melon' },
    { char: '🍉', name: 'watermelon' },
    { char: '🍊', name: 'tangerine' },
    { char: '🍋', name: 'lemon' },
    { char: '🍌', name: 'banana' },
    { char: '🍍', name: 'pineapple' },
    { char: '🍎', name: 'red apple' },
    { char: '🍏', name: 'green apple' },
    { char: '🍐', name: 'pear' },
    { char: '🍑', name: 'peach' },
    { char: '🍒', name: 'cherries' },
    { char: '🍓', name: 'strawberry' },
    { char: '💐', name: 'bouquet' },
    { char: '🥀', name: 'wilted flower' },
    { char: '🥝', name: 'kiwi fruit' },
    { char: '🥭', name: 'mango' },
    { char: '💮', name: 'white flower' },
    { char: '⚽', name: 'soccer ball' },
    { char: '⚾', name: 'baseball' },
    { char: '🎣', name: 'fishing pole' },
    { char: '🎽', name: 'running shirt' },
    { char: '🎾', name: 'tennis' },
    { char: '🎿', name: 'skis' },
    { char: '🏀', name: 'basketball' },
    { char: '🏁', name: 'chequered flag' },
    { char: '🏂', name: 'snowboarder' },
    { char: '🏃', name: 'person running' },
    { char: '🏄', name: 'person surfing' },
    { char: '🏅', name: 'sports medal' },
    { char: '🏆', name: 'trophy' },
    { char: '🏇', name: 'horse racing' },
    { char: '🏈', name: 'american football' },
    { char: '🏉', name: 'rugby football' },
    { char: '🏊', name: 'person swimming' },
    { char: '🏋', name: 'person lifting weights' },
    { char: '🏌', name: 'person golfing' },
    { char: '🏏', name: 'cricket game' },
    { char: '🏐', name: 'volleyball' },
    { char: '🏑', name: 'field hockey' },
    { char: '🏒', name: 'ice hockey' },
    { char: '🏓', name: 'ping pong' },
    { char: '🏸', name: 'badminton' },
    { char: '🏹', name: 'bow and arrow' },
    { char: '🤸', name: 'person cartwheeling' },
    { char: '🤹', name: 'person juggling' },
    { char: '🤺', name: 'person fencing' },
    { char: '🤻', name: 'modern pentathlon' },
    { char: '🤼', name: 'people wrestling' },
    { char: '🤽', name: 'person playing water polo' },
    { char: '🤾', name: 'person playing handball' },
    { char: '🤿', name: 'diving mask' },
    { char: '🥅', name: 'goal net' },
    { char: '🥆', name: 'rifle' },
    { char: '🥇', name: '1st place medal' },
    { char: '🥈', name: '2nd place medal' },
    { char: '🥉', name: '3rd place medal' },
    { char: '🥊', name: 'boxing glove' },
    { char: '🥋', name: 'martial arts uniform' },
    { char: '🥌', name: 'curling stone' },
    { char: '🥍', name: 'lacrosse' },
    { char: '🥎', name: 'softball' },
    { char: '🥏', name: 'flying disc' },
    { char: '🎮', name: 'video game' },
    { char: '🎯', name: 'direct hit' },
    { char: '🎰', name: 'slot machine' },
    { char: '🎱', name: 'pool 8 ball' },
    { char: '🎲', name: 'game die' },
    { char: '🎳', name: 'bowling' },
    { char: '🎴', name: 'flower playing cards' },
    { char: '🧩', name: 'puzzle piece' },
    { char: '🌌', name: 'milky way' },
    { char: '🌍', name: 'globe showing Europe-Africa' },
    { char: '🌎', name: 'globe showing Americas' },
    { char: '🌏', name: 'globe showing Asia-Australia' },
    { char: '🌐', name: 'globe with meridians' },
    { char: '🌑', name: 'new moon' },
    { char: '🌒', name: 'waxing crescent moon' },
    { char: '🌓', name: 'first quarter moon' },
    { char: '🌔', name: 'waxing gibbous moon' },
    { char: '🌕', name: 'full moon' },
    { char: '🌖', name: 'waning gibbous moon' },
    { char: '🌗', name: 'last quarter moon' },
    { char: '🌘', name: 'waning crescent moon' },
    { char: '🌙', name: 'crescent moon' },
    { char: '🌚', name: 'new moon face' },
    { char: '🌛', name: 'first quarter moon face' },
    { char: '🌜', name: 'last quarter moon face' },
    { char: '🌝', name: 'full moon face' },
    { char: '🌞', name: 'sun with face' },
    { char: '🌟', name: 'glowing star' },
    { char: '🌠', name: 'shooting star' },
    { char: '🌡', name: 'thermometer' },
    { char: '🌤', name: 'white sun with small cloud' },
    { char: '🌥', name: 'white sun behind cloud' },
    { char: '🌦', name: 'white sun behind cloud with rain' },
    { char: '🌧', name: 'cloud with rain' },
    { char: '🌨', name: 'cloud with snow' },
    { char: '🌩', name: 'cloud with lightning' },
    { char: '🌪', name: 'tornado' },
    { char: '🌫', name: 'fog' },
    { char: '🌬', name: 'wind face' },
    { char: '👔', name: 'necktie' },
    { char: '👕', name: 't-shirt' },
    { char: '👖', name: 'jeans' },
    { char: '👗', name: 'dress' },
    { char: '👘', name: 'kimono' },
    { char: '👙', name: 'bikini' },
    { char: '👚', name: 'woman’s clothes' },
    { char: '🥻', name: 'sari' },
    { char: '🥼', name: 'lab coat' },
    { char: '🦺', name: 'safety vest' },
    { char: '🧥', name: 'coat' },
    { char: '🩱', name: 'one-piece swimsuit' },
    { char: '🩲', name: 'briefs' },
    { char: '🩳', name: 'shorts' },
    { char: '🩴', name: 'thong sandal' },
    { char: '👞', name: 'man’s shoe' },
    { char: '👟', name: 'running shoe' },
    { char: '👠', name: 'high-heeled shoe' },
    { char: '👡', name: 'woman’s sandal' },
    { char: '👢', name: 'woman’s boot' },
    { char: '🥾', name: 'hiking boot' },
    { char: '🥿', name: 'flat shoe' },
    { char: '🧦', name: 'socks' },
    { char: '🩰', name: 'ballet shoes' },
    { char: '🎓', name: 'graduation cap' },
    { char: '🎩', name: 'top hat' },
    { char: '👑', name: 'crown' },
    { char: '👒', name: 'woman’s hat' },
    { char: '🧢', name: 'billed cap' },
    { char: '👓', name: 'glasses' },
    { char: '👛', name: 'purse' },
    { char: '👜', name: 'handbag' },
    { char: '👝', name: 'pouch' },
    { char: '🥽', name: 'goggles' },
    { char: '🧣', name: 'scarf' },
    { char: '🧤', name: 'gloves' },
    { char: '🎘', name: 'musical keyboard with jacks' },
    { char: '🎙', name: 'studio microphone' },
    { char: '🎚', name: 'level slider' },
    { char: '🎛', name: 'control knobs' },
    { char: '🎜', name: 'beamed ascending musical notes' },
    { char: '🎝', name: 'beamed descending musical notes' },
    { char: '🎞', name: 'film frames' },
    { char: '🎤', name: 'microphone' },
    { char: '🎥', name: 'movie camera' },
    { char: '🎦', name: 'cinema' },
    { char: '🎧', name: 'headphone' },
    { char: '🎬', name: 'clapper board' },
    { char: '🎵', name: 'musical note' },
    { char: '🎶', name: 'musical notes' },
    { char: '🎷', name: 'saxophone' },
    { char: '🎸', name: 'guitar' },
    { char: '🎹', name: 'musical keyboard' },
    { char: '🎺', name: 'trumpet' },
    { char: '🎻', name: 'violin' },
    { char: '🎼', name: 'musical score' },
    { char: '🥁', name: 'drum' },
    { char: '🪇', name: 'maracas' },
    { char: '🪈', name: 'flute' },
    { char: '📷', name: 'camera' },
    { char: '📸', name: 'camera with flash' },
    { char: '📹', name: 'video camera' },
    { char: '📺', name: 'television' },
    { char: '📻', name: 'radio' },
    { char: '📼', name: 'videocassette' },
    { char: '📽', name: 'film projector' },
    { char: '📾', name: 'portable stereo' },
    { char: '🔇', name: 'muted speaker' },
    { char: '🔈', name: 'speaker low volume' },
    { char: '🔉', name: 'speaker medium volume' },
    { char: '🔊', name: 'speaker high volume' },
    { char: '🕨', name: 'speaker with cancellation stroke' },
    { char: '🕩', name: 'speaker with one sound wave' },
    { char: '🕪', name: 'speaker with three sound waves' },
    { char: '🕫', name: 'bullhorn' },
    { char: '🕬', name: 'bullhorn with sound waves' },
    { char: '🕭', name: 'ringing bell' },
    { char: '🕮', name: 'book' },
    { char: '🕯', name: 'candle' },
    { char: '🕰', name: 'mantelpiece clock' },
    { char: '🕱', name: 'black skull and crossbones' },
    { char: '🕲', name: 'no piracy' },
    { char: '🕳', name: 'hole' },
    { char: '🕶', name: 'sunglasses' },
    { char: '🕹', name: 'joystick' },
    { char: '⏩', name: 'fast-forward button' },
    { char: '⏪', name: 'fast reverse button' },
    { char: '⏫', name: 'fast up button' },
    { char: '⏬', name: 'fast down button' },
    { char: '⏭', name: 'next track button' },
    { char: '⏮', name: 'last track button' },
    { char: '⏯', name: 'play or pause button' },
    { char: '⏴', name: 'reverse button' },
    { char: '⏵', name: 'play button' },
    { char: '⏶', name: 'up button' },
    { char: '⏷', name: 'down button' },
    { char: '⏸', name: 'pause button' },
    { char: '⏹', name: 'stop button' },
    { char: '⏺', name: 'record button' },
    { char: '🔀', name: 'shuffle tracks button' },
    { char: '🔁', name: 'repeat button' },
    { char: '🔂', name: 'repeat single button' },
    { char: '🔃', name: 'clockwise vertical arrows' },
    { char: '🔄', name: 'anticlockwise arrows button' },
    { char: '🔅', name: 'low brightness' },
    { char: '🔆', name: 'high brightness' },
    { char: '🔼', name: 'upwards button' },
    { char: '🔽', name: 'downwards button' },
    { char: '🎟', name: 'admission tickets' },
    { char: '🎠', name: 'carousel horse' },
    { char: '🎡', name: 'ferris wheel' },
    { char: '🎢', name: 'roller coaster' },
    { char: '🎨', name: 'artist palette' },
    { char: '🎪', name: 'circus tent' },
    { char: '🎫', name: 'ticket' },
    { char: '🎭', name: 'performing arts' },
    { char: '💯', name: 'hundred points' },
    { char: '🪀', name: 'yo-yo' },
    { char: '🪁', name: 'kite' },
    { char: '🪂', name: 'parachute' },
    { char: '🪃', name: 'boomerang' },
    { char: '🪄', name: 'magic wand' },
    { char: '🪅', name: 'piñata' },
    { char: '🪆', name: 'nesting dolls' },
    { char: '🎀', name: 'ribbon' },
    { char: '🎁', name: 'wrapped gift' },
    { char: '🎂', name: 'birthday cake' },
    { char: '🎃', name: 'jack-o-lantern' },
    { char: '🎄', name: 'christmas tree' },
    { char: '🎆', name: 'fireworks' },
    { char: '🎇', name: 'sparkler' },
    { char: '🎈', name: 'balloon' },
    { char: '🎉', name: 'party popper' },
    { char: '🎊', name: 'confetti ball' },
    { char: '🎋', name: 'tanabata tree' },
    { char: '🎌', name: 'crossed flags' },
    { char: '🎍', name: 'pine decoration' },
    { char: '🎎', name: 'japanese dolls' },
    { char: '🎏', name: 'carp streamer' },
    { char: '🎐', name: 'wind chime' },
    { char: '🎑', name: 'moon viewing ceremony' },
    { char: '🎒', name: 'school backpack' },
    { char: '🎔', name: 'heart with tip' },
    { char: '🎕', name: 'bouquet' },
    { char: '🎖', name: 'military medal' },
    { char: '🎗', name: 'reminder ribbon' },
    { char: '🧧', name: 'red envelope' },
    { char: '🧨', name: 'firecracker' },
    { char: '💰', name: 'money bag' },
    { char: '💱', name: 'currency exchange' },
    { char: '💲', name: 'heavy dollar sign' },
    { char: '💳', name: 'credit card' },
    { char: '💴', name: 'yen banknote' },
    { char: '💵', name: 'dollar banknote' },
    { char: '💶', name: 'euro banknote' },
    { char: '💷', name: 'pound banknote' },
    { char: '💸', name: 'money with wings' },
    { char: '💹', name: 'chart increasing with yen' },
    { char: '📿', name: 'prayer beads' },
    { char: '🔍', name: 'magnifying glass tilted left' },
    { char: '🔎', name: 'magnifying glass tilted right' },
    { char: '🔏', name: 'locked with pen' },
    { char: '🔐', name: 'locked with key' },
    { char: '🔑', name: 'key' },
    { char: '🔒', name: 'locked' },
    { char: '🔓', name: 'unlocked' },
    { char: '🔦', name: 'flashlight' },
    { char: '🔧', name: 'wrench' },
    { char: '🔨', name: 'hammer' },
    { char: '🔩', name: 'nut and bolt' },
    { char: '🔬', name: 'microscope' },
    { char: '🔭', name: 'telescope' },
    { char: '🧭', name: 'compass' },
    { char: '🧰', name: 'toolbox' },
    { char: '🧲', name: 'magnet' },
    { char: '🔲', name: 'black square button' },
    { char: '🔳', name: 'white square button' },
    { char: '🔴', name: 'red circle' },
    { char: '🔵', name: 'blue circle' },
    { char: '🔶', name: 'large orange diamond' },
    { char: '🔷', name: 'large blue diamond' },
    { char: '🔸', name: 'small orange diamond' },
    { char: '🔹', name: 'small blue diamond' },
    { char: '🔺', name: 'red triangle pointed up' },
    { char: '🔻', name: 'red triangle pointed down' },
    { char: '🔘', name: 'radio button' },
    { char: '🔙', name: 'BACK arrow' },
    { char: '🔚', name: 'END arrow' },
    { char: '🔛', name: 'ON! arrow' },
    { char: '🔜', name: 'SOON arrow' },
    { char: '🔝', name: 'TOP arrow' },
    { char: '🔞', name: 'no one under eighteen' },
    { char: '🔟', name: 'keycap: 10' },
    { char: '🔠', name: 'input latin uppercase' },
    { char: '🔡', name: 'input latin lowercase' },
    { char: '🔢', name: 'input numbers' },
    { char: '🔣', name: 'input symbols' },
    { char: '🔤', name: 'input latin letters' },
    { char: '🏻', name: 'light skin tone' },
    { char: '🏼', name: 'medium-light skin tone' },
    { char: '🏽', name: 'medium skin tone' },
    { char: '🏾', name: 'medium-dark skin tone' },
    { char: '🏿', name: 'dark skin tone' },
    { char: '💠', name: 'diamond with a dot' },
    { char: '💡', name: 'light bulb' },
    { char: '💢', name: 'anger symbol' },
    { char: '💣', name: 'bomb' },
    { char: '💥', name: 'collision' },
    { char: '💦', name: 'splashing sweat' },
    { char: '💧', name: 'droplet' },
    { char: '💨', name: 'dashing away' },
    { char: '🔔', name: 'bell' },
    { char: '🔕', name: 'bell with slash' },
    { char: '🔖', name: 'bookmark' },
    { char: '🔗', name: 'link' },
    { char: '🔥', name: 'fire' },
    { char: '🔫', name: 'pistol' },
    { char: '🔮', name: 'crystal ball' },
    { char: '🔰', name: 'japanese symbol for beginner' },
    { char: '🔱', name: 'trident emblem' },
    { char: '🧪', name: 'test tube' },
    { char: '🧫', name: 'petri dish' },
    { char: '🧬', name: 'dna' },
    { char: '🧮', name: 'abacus' },
    { char: '🧯', name: 'fire extinguisher' },
    { char: '🧱', name: 'brick' },
    { char: '🧳', name: 'luggage' },
    { char: '🧴', name: 'lotion bottle' },
    { char: '🧵', name: 'thread' },
    { char: '🧶', name: 'yarn' },
    { char: '🧷', name: 'safety pin' },
    { char: '🧸', name: 'teddy bear' },
    { char: '🧹', name: 'broom' },
    { char: '🧺', name: 'basket' },
    { char: '🧻', name: 'roll of paper' },
    { char: '🧼', name: 'soap' },
    { char: '🧽', name: 'sponge' },
    { char: '🧾', name: 'receipt' },
    { char: '🧿', name: 'nazar amulet' },
    { char: '🏱', name: 'white pennant' },
    { char: '🏲', name: 'black pennant' },
    { char: '🏳', name: 'white flag' },
    { char: '🏴', name: 'black flag' },
    { char: '🏵', name: 'rosette' },
    { char: '🏶', name: 'black rosette' },
    { char: '🏷', name: 'label' },
    { char: '🕬', name: 'bullhorn with sound waves' },
    { char: '🕭', name: 'ringing bell' },
    { char: '🕮', name: 'book' },
    { char: '🕯', name: 'candle' },
    { char: '🕰', name: 'mantelpiece clock' },
    { char: '🕱', name: 'black skull and crossbones' },
    { char: '🕲', name: 'no piracy' },
    { char: '🕳', name: 'hole' },
    { char: '🕶', name: 'sunglasses' },
    { char: '🕹', name: 'joystick' },
];
