
export type EmojiSymbol = {
    char: string;
    name: string;
};

export type EmojiCategory = {
    name: string;
    icon: string;
    symbols: EmojiSymbol[];
};

export const emojiCategories: EmojiCategory[] = [
    {
        name: "Smileys & People",
        icon: "😀",
        symbols: [
            { char: '😀', name: 'grinning face' },
            { char: '😁', name: 'grinning face with smiling eyes' },
            { char: '😂', name: 'face with tears of joy' },
            { char: '😃', name: 'smiling face with open mouth' },
            { char: '😄', name: 'smiling face with open mouth and smiling eyes' },
            { char: '😅', name: 'smiling face with open mouth and cold sweat' },
            { char: '😆', name: 'smiling face with open mouth and tightly-closed eyes' },
            { char: '😇', name: 'smiling face with halo' },
            { char: '😈', name: 'smiling face with horns' },
            { char: '😉', name: 'winking face' },
            { char: '😊', name: 'smiling face with smiling eyes' },
            { char: '😋', name: 'face savouring delicious food' },
            { char: '😌', name: 'relieved face' },
            { char: '😍', name: 'smiling face with heart-shaped eyes' },
            { char: '😎', name: 'smiling face with sunglasses' },
            { char: '😏', name: 'smirking face' },
            { char: '😐', name: 'neutral face' },
            { char: '😑', name: 'expressionless face' },
            { char: '😒', name: 'unamused face' },
            { char: '😓', name: 'face with cold sweat' },
            { char: '😔', name: 'pensive face' },
            { char: '😕', name: 'confused face' },
            { char: '😖', name: 'confounded face' },
            { char: '😗', name: 'kissing face' },
            { char: '😘', name: 'face throwing a kiss' },
            { char: '😙', name: 'kissing face with smiling eyes' },
            { char: '😚', name: 'kissing face with closed eyes' },
            { char: '😛', name: 'face with stuck-out tongue' },
            { char: '😜', name: 'face with stuck-out tongue and winking eye' },
            { char: '😝', name: 'face with stuck-out tongue and tightly-closed eyes' },
            { char: '😞', name: 'disappointed face' },
            { char: '😟', name: 'worried face' },
            { char: '😠', name: 'angry face' },
            { char: '😡', name: 'pouting face' },
            { char: '😢', name: 'crying face' },
            { char: '😣', name: 'persevering face' },
            { char: '😤', name: 'face with look of triumph' },
            { char: '😥', name: 'disappointed but relieved face' },
            { char: '😦', name: 'frowning face with open mouth' },
            { char: '😧', name: 'anguished face' },
            { char: '😨', name: 'fearful face' },
            { char: '😩', name: 'weary face' },
            { char: '😪', name: 'sleepy face' },
            { char: '😫', name: 'tired face' },
            { char: '😬', name: 'grimacing face' },
            { char: '😭', name: 'loudly crying face' },
            { char: '😮', name: 'face with open mouth' },
            { char: '😯', name: 'hushed face' },
            { char: '😰', name: 'face with open mouth and cold sweat' },
            { char: '😱', name: 'face screaming in fear' },
            { char: '😲', name: 'astonished face' },
            { char: '😳', name: 'flushed face' },
            { char: '😴', name: 'sleeping face' },
            { char: '😵', name: 'dizzy face' },
            { char: '😶', name: 'face without mouth' },
            { char: '😷', name: 'face with medical mask' },
            { char: '🙁', name: 'slightly frowning face' },
            { char: '🙂', name: 'slightly smiling face' },
            { char: '🙃', name: 'upside-down face' },
            { char: '🙄', name: 'face with rolling eyes' },
            { char: '🤐', name: 'zipper-mouth face' },
            { char: '🤑', name: 'money-mouth face' },
            { char: '🤒', name: 'face with thermometer' },
            { char: '🤓', name: 'nerd face' },
            { char: '🤔', name: 'thinking face' },
            { char: '🤕', name: 'face with head-bandage' },
            { char: '🤗', name: 'hugging face' },
            { char: '🤠', name: 'cowboy hat face' },
            { char: '🤢', name: 'nauseated face' },
            { char: '🤣', name: 'rolling on the floor laughing' },
            { char: '🤤', name: 'drooling face' },
            { char: '🤥', name: 'lying face' },
            { char: '🤧', name: 'sneezing face' },
            { char: '🤨', name: 'face with raised eyebrow' },
            { char: '🤩', name: 'star-struck' },
            { char: '🤪', name: 'zany face' },
            { char: '🤫', name: 'shushing face' },
            { char: '🤭', name: 'face with hand over mouth' },
            { char: '🤮', name: 'face vomiting' },
            { char: '🤯', name: 'exploding head' },
            { char: '🥰', name: 'smiling face with hearts' },
            { char: '🥱', name: 'yawning face' },
            { char: '🥳', name: 'partying face' },
            { char: '🥴', name: 'woozy face' },
            { char: '🥵', name: 'hot face' },
            { char: '🥶', name: 'cold face' },
            { char: '🥺', name: 'pleading face' },
            { char: '🧐', name: 'face with monocle' },
            { char: '😸', name: 'grinning cat face with smiling eyes' },
            { char: '😹', name: 'cat face with tears of joy' },
            { char: '😺', name: 'smiling cat face with open mouth' },
            { char: '😻', name: 'smiling cat face with heart-eyes' },
            { char: '😼', name: 'cat face with wry smile' },
            { char: '😽', name: 'kissing cat face' },
            { char: '😾', name: 'pouting cat face' },
            { char: '😿', name: 'crying cat face' },
            { char: '🙀', name: 'weary cat face' },
            { char: '🙈', name: 'see-no-evil monkey' },
            { char: '🙉', name: 'hear-no-evil monkey' },
            { char: '🙊', name: 'speak-no-evil monkey' },
            { char: '👿', name: 'angry face with horns' },
            { char: '💀', name: 'skull' },
            { char: '🤬', name: 'face with symbols on mouth' },
            { char: '✋', name: 'raised hand' },
            { char: '👋', name: 'waving hand' },
            { char: '🖐', name: 'hand with fingers splayed' },
            { char: '🖖', name: 'vulcan salute' },
            { char: '🤚', name: 'raised back of hand' },
            { char: '☝', name: 'index pointing up' },
            { char: '👆', name: 'backhand index pointing up' },
            { char: '👇', name: 'backhand index pointing down' },
            { char: '👈', name: 'backhand index pointing left' },
            { char: '👉', name: 'backhand index pointing right' },
            { char: '🖕', name: 'middle finger' },
            { char: '✊', name: 'raised fist' },
            { char: '👊', name: 'oncoming fist' },
            { char: '👍', name: 'thumbs up' },
            { char: '👎', name: 'thumbs down' },
            { char: '🤛', name: 'left-facing fist' },
            { char: '🤜', name: 'right-facing fist' },
            { char: '✌', name: 'victory hand' },
            { char: '👌', name: 'OK hand' },
            { char: '🤏', name: 'pinching hand' },
            { char: '🤘', name: 'sign of the horns' },
            { char: '🤙', name: 'call me hand' },
            { char: '🤞', name: 'crossed fingers' },
            { char: '🤟', name: 'love-you gesture' },
            { char: '✍', name: 'writing hand' },
            { char: '👏', name: 'clapping hands' },
            { char: '👐', name: 'open hands' },
            { char: '💅', name: 'nail polish' },
            { char: '🤝', name: 'handshake' },
            { char: '🤲', name: 'palms up together' },
            { char: '🤳', name: 'selfie' },
            { char: '👮', name: 'police officer' },
            { char: '👯', name: 'people with bunny ears' },
            { char: '👰', name: 'bride with veil' },
            { char: '👲', name: 'man with gua pi mao' },
            { char: '👳', name: 'man with turban' },
            { char: '👷', name: 'construction worker' },
            { char: '👸', name: 'princess' },
            { char: '🕴', name: 'man in suit levitating' },
            { char: '🕵', name: 'detective' },
            { char: '💁', name: 'information desk person' },
            { char: '💂', name: 'guard' },
            { char: '💃', name: 'woman dancing' },
            { char: '🤴', name: 'prince' },
            { char: '🤵', name: 'man in tuxedo' },
            { char: '👪', name: 'family' },
            { char: '👫', name: 'man and woman holding hands' },
            { char: '👬', name: 'two men holding hands' },
            { char: '👭', name: 'two women holding hands' },
            { char: '💏', name: 'kiss' },
            { char: '💑', name: 'couple with heart' },
            { char: '🤰', name: 'pregnant woman' },
            { char: '🤱', name: 'breast-feeding' },
            { char: '👤', name: 'bust in silhouette' },
            { char: '👥', name: 'busts in silhouette' },
            { char: '👦', name: 'boy' },
            { char: '👧', name: 'girl' },
            { char: '👨', name: 'man' },
            { char: '👩', name: 'woman' },
            { char: '👱', name: 'person with blond hair' },
            { char: '👴', name: 'old man' },
            { char: '👵', name: 'old woman' },
            { char: '👶', name: 'baby' },
            { char: '🕺', name: 'man dancing' },
            { char: '🧍', name: 'person standing' },
            { char: '🧎', name: 'person kneeling' },
            { char: '🧑', name: 'adult' },
            { char: '🧒', name: 'child' },
            { char: '🧓', name: 'older adult' },
            { char: '🧔', name: 'man with beard' },
            { char: '🧕', name: 'woman with headscarf' },
            { char: '🧖', name: 'person in steamy room' },
            { char: '🧗', name: 'person climbing' },
            { char: '🧘', name: 'person in lotus position' },
            { char: '🦰', name: 'red hair' },
            { char: '🦱', name: 'curly hair' },
            { char: '🦲', name: 'bald' },
            { char: '🦳', name: 'white hair' },
            { char: '💆', name: 'person getting massage' },
            { char: '💇', name: 'person getting haircut' },
            { char: '🙅', name: 'person gesturing NO' },
            { char: '🙆', name: 'person gesturing OK' },
            { char: '🙇', name: 'person bowing' },
            { char: '🙋', name: 'person raising hand' },
            { char: '🙌', name: 'raising hands' },
            { char: '🙍', name: 'person frowning' },
            { char: '🙎', name: 'person pouting' },
            { char: '🙏', name: 'folded hands' },
            { char: '🤦', name: 'face palm' },
            { char: '🤷', name: 'shrug' },
            { char: '🧏', name: 'deaf person' },
            { char: '🎅', name: 'Santa Claus' },
            { char: '👹', name: 'Japanese Ogre' },
            { char: '👺', name: 'Japanese Goblin' },
            { char: '👻', name: 'ghost' },
            { char: '👼', name: 'baby angel' },
            { char: '👽', name: 'alien' },
            { char: '👾', name: 'alien monster' },
            { char: '🤖', name: 'robot face' },
            { char: '🤡', name: 'clown face' },
            { char: '🤶', name: 'Mrs. Claus' },
            { char: '🦸', name: 'superhero' },
            { char: '🦹', name: 'supervillain' },
            { char: '🧙', name: 'mage' },
            { char: '🧚', name: 'fairy' },
            { char: '🧛', name: 'vampire' },
            { char: '🧜', name: 'merperson' },
            { char: '🧝', name: 'elf' },
            { char: '🧞', name: 'genie' },
            { char: '🧟', name: 'zombie' },
            { char: '👀', name: 'eyes' },
            { char: '👁', name: 'eye' },
            { char: '👂', name: 'ear' },
            { char: '👃', name: 'nose' },
            { char: '👄', name: 'mouth' },
            { char: '👅', name: 'tongue' },
            { char: '👣', name: 'footprints' },
            { char: '💪', name: 'flexed biceps' },
            { char: '🦴', name: 'bone' },
            { char: '🦵', name: 'leg' },
            { char: '🦶', name: 'foot' },
            { char: '🦷', name: 'tooth' },
            { char: '🦻', name: 'ear with hearing aid' },
            { char: '🦼', name: 'motorized wheelchair' },
            { char: '🦽', name: 'manual wheelchair' },
            { char: '🦾', name: 'mechanical arm' },
            { char: '🦿', name: 'mechanical leg' },
            { char: '🧠', name: 'brain' },
        ],
    },
    {
        name: "Animals & Nature",
        icon: "🐶",
        symbols: [
            { char: '🐀', name: 'rat' },
            { char: '🐁', name: 'mouse' },
            { char: '🐂', name: 'ox' },
            { char: '🐃', name: 'water buffalo' },
            { char: '🐄', name: 'cow' },
            { char: '🐅', name: 'tiger' },
            { char: '🐆', name: 'leopard' },
            { char: '🐇', name: 'rabbit' },
            { char: '🐈', name: 'cat' },
            { char: '🐉', name: 'dragon' },
            { char: '🐊', name: 'crocodile' },
            { char: '🐋', name: 'whale' },
            { char: '🐌', name: 'snail' },
            { char: '🐍', name: 'snake' },
            { char: '🐎', name: 'horse' },
            { char: '🐏', name: 'ram' },
            { char: '🐐', name: 'goat' },
            { char: '🐑', name: 'ewe' },
            { char: '🐒', name: 'monkey' },
            { char: '🐓', name: 'rooster' },
            { char: '🐔', name: 'chicken' },
            { char: '🐕', name: 'dog' },
            { char: '🐖', name: 'pig' },
            { char: '🐗', name: 'boar' },
            { char: '🐘', name: 'elephant' },
            { char: '🐙', name: 'octopus' },
            { char: '🐚', name: 'spiral shell' },
            { char: '🐛', name: 'bug' },
            { char: '🐜', name: 'ant' },
            { char: '🐝', name: 'honeybee' },
            { char: '🐞', name: 'lady beetle' },
            { char: '🐟', name: 'fish' },
            { char: '🐠', name: 'tropical fish' },
            { char: '🐡', name: 'blowfish' },
            { char: '🐢', name: 'turtle' },
            { char: '🐣', name: 'hatching chick' },
            { char: '🐤', name: 'baby chick' },
            { char: '🐥', name: 'front-facing baby chick' },
            { char: '🐦', name: 'bird' },
            { char: '🐧', name: 'penguin' },
            { char: '🐨', name: 'koala' },
            { char: '🐩', name: 'poodle' },
            { char: '🐪', name: 'dromedary' },
            { char: '🐫', name: 'two-hump camel' },
            { char: '🐬', name: 'dolphin' },
            { char: '🐭', name: 'mouse face' },
            { char: '🐮', name: 'cow face' },
            { char: '🐯', name: 'tiger face' },
            { char: '🐰', name: 'rabbit face' },
            { char: '🐱', name: 'cat face' },
            { char: '🐲', name: 'dragon face' },
            { char: '🐳', name: 'spouting whale' },
            { char: '🐴', name: 'horse face' },
            { char: '🐵', name: 'monkey face' },
            { char: '🐶', name: 'dog face' },
            { char: '🐷', name: 'pig face' },
            { char: '🐸', name: 'frog face' },
            { char: '🐹', name: 'hamster face' },
            { char: '🐺', name: 'wolf face' },
            { char: '🐻', name: 'bear face' },
            { char: '🐼', name: 'panda face' },
            { char: '🐽', name: 'pig nose' },
            { char: '🐾', name: 'paw prints' },
            { char: '🐿', name: 'chipmunk' },
            { char: '🕷', name: 'spider' },
            { char: '🕸', name: 'spider web' },
            { char: '🦀', name: 'crab' },
            { char: '🦁', name: 'lion face' },
            { char: '🦂', name: 'scorpion' },
            { char: '🦃', name: 'turkey' },
            { char: '🦄', name: 'unicorn face' },
            { char: '🦅', name: 'eagle' },
            { char: '🦆', name: 'duck' },
            { char: '🦇', name: 'bat' },
            { char: '🦈', name: 'shark' },
            { char: '🦉', name: 'owl' },
            { char: '🦊', name: 'fox face' },
            { char: '🦋', name: 'butterfly' },
            { char: '🦌', name: 'deer' },
            { char: '🦍', name: 'gorilla' },
            { char: '🦎', name: 'lizard' },
            { char: '🦏', name: 'rhinoceros' },
            { char: '🦐', name: 'shrimp' },
            { char: '🦑', name: 'squid' },
            { char: '🦒', name: 'giraffe face' },
            { char: '🦓', name: 'zebra face' },
            { char: '🦔', name: 'hedgehog' },
            { char: '🦕', name: 'sauropod' },
            { char: '🦖', name: 'T-Rex' },
            { char: '🦗', name: 'cricket' },
            { char: '🦘', name: 'kangaroo' },
            { char: '🦙', name: 'llama' },
            { char: '🦚', name: 'peacock' },
            { char: '🦛', name: 'hippopotamus' },
            { char: '🦜', name: 'parrot' },
            { char: '🦝', name: 'raccoon' },
            { char: '🦞', name: 'lobster' },
            { char: '🦟', name: 'mosquito' },
            { char: '🦠', name: 'microbe' },
            { char: '🦡', name: 'badger' },
            { char: '🦢', name: 'swan' },
            { char: '🦣', name: 'mammoth' },
            { char: '🦤', name: 'dodo' },
            { char: '🦥', name: 'sloth' },
            { char: '🦦', name: 'otter' },
            { char: '🦧', name: 'orangutan' },
            { char: '🦨', name: 'skunk' },
            { char: '🦩', name: 'flamingo' },
            { char: '🦪', name: 'oyster' },
            { char: '🦫', name: 'beaver' },
            { char: '🦬', name: 'bison' },
            { char: '🦭', name: 'seal' },
            { char: '🦮', name: 'guide dog' },
            { char: '🦯', name: 'probing cane' },
            { char: '🌰', name: 'chestnut' },
            { char: '🌱', name: 'seedling' },
            { char: '🌲', name: 'evergreen tree' },
            { char: '🌳', name: 'deciduous tree' },
            { char: '🌴', name: 'palm tree' },
            { char: '🌵', name: 'cactus' },
            { char: '🌶', name: 'hot pepper' },
            { char: '🌷', name: 'tulip' },
            { char: '🌸', name: 'cherry blossom' },
            { char: '🌹', name: 'rose' },
            { char: '🌺', name: 'hibiscus' },
            { char: '🌻', name: 'sunflower' },
            { char: '🌼', name: 'blossom' },
            { char: '🌿', name: 'herb' },
            { char: '🍀', name: 'four leaf clover' },
            { char: '🍁', name: 'maple leaf' },
            { char: '🍂', name: 'fallen leaf' },
            { char: '🍃', name: 'leaf fluttering in wind' },
            { char: '💐', name: 'bouquet' },
            { char: '🥀', name: 'wilted flower' },
            { char: '💮', name: 'white flower' },
            { char: '🌌', name: 'milky way' },
            { char: '🌍', name: 'globe showing Europe-Africa' },
            { char: '🌎', name: 'globe showing Americas' },
            { char: '🌏', name: 'globe showing Asia-Australia' },
            { char: '🌐', name: 'globe with meridians' },
            { char: '🌑', name: 'new moon' },
            { char: '🌒', name: 'waxing crescent moon' },
            { char: '🌓', name: 'first quarter moon' },
            { char: '🌔', name: 'waxing gibbous moon' },
            { char: '🌕', name: 'full moon' },
            { char: '🌖', name: 'waning gibbous moon' },
            { char: '🌗', name: 'last quarter moon' },
            { char: '🌘', name: 'waning crescent moon' },
            { char: '🌙', name: 'crescent moon' },
            { char: '🌚', name: 'new moon face' },
            { char: '🌛', name: 'first quarter moon face' },
            { char: '🌜', name: 'last quarter moon face' },
            { char: '🌝', name: 'full moon face' },
            { char: '🌞', name: 'sun with face' },
            { char: '🌟', name: 'glowing star' },
            { char: '🌠', name: 'shooting star' },
            { char: '🌡', name: 'thermometer' },
            { char: '🌤', name: 'white sun with small cloud' },
            { char: '🌥', name: 'white sun behind cloud' },
            { char: '🌦', name: 'white sun behind cloud with rain' },
            { char: '🌧', name: 'cloud with rain' },
            { char: '🌨', name: 'cloud with snow' },
            { char: '🌩', name: 'cloud with lightning' },
            { char: '🌪', name: 'tornado' },
            { char: '🌫', name: 'fog' },
            { char: '🌬', name: 'wind face' },
        ],
    },
    {
        name: "Food & Drink",
        icon: "🍔",
        symbols: [
            { char: '🍇', name: 'grapes' },
            { char: '🍈', name: 'melon' },
            { char: '🍉', name: 'watermelon' },
            { char: '🍊', name: 'tangerine' },
            { char: '🍋', name: 'lemon' },
            { char: '🍌', name: 'banana' },
            { char: '🍍', name: 'pineapple' },
            { char: '🍎', name: 'red apple' },
            { char: '🍏', name: 'green apple' },
            { char: '🍐', name: 'pear' },
            { char: '🍑', name: 'peach' },
            { char: '🍒', name: 'cherries' },
            { char: '🍓', name: 'strawberry' },
            { char: '🥝', name: 'kiwi fruit' },
            { char: '🥭', name: 'mango' },
            { char: '☕', name: 'hot beverage' },
            { char: '🍵', name: 'teacup without handle' },
            { char: '🍶', name: 'sake' },
            { char: '🍷', name: 'wine glass' },
            { char: '🍸', name: 'cocktail glass' },
            { char: '🍹', name: 'tropical drink' },
            { char: '🍺', name: 'beer mug' },
            { char: '🍻', name: 'clinking beer mugs' },
            { char: '🍼', name: 'baby bottle' },
            { char: '🍾', name: 'bottle with popping cork' },
            { char: '🏺', name: 'amphora' },
            { char: '🥂', name: 'clinking glasses' },
            { char: '🥃', name: 'tumbler glass' },
            { char: '🥛', name: 'glass of milk' },
            { char: '🥤', name: 'cup with straw' },
            { char: '🧃', name: 'beverage box' },
            { char: '🧉', name: 'mate' },
            { char: '🧊', name: 'ice' },
            { char: '🌭', name: 'hot dog' },
            { char: '🌮', name: 'taco' },
            { char: '🌯', name: 'burrito' },
            { char: '🍔', name: 'hamburger' },
            { char: '🍕', name: 'pizza' },
            { char: '🍖', name: 'meat on bone' },
            { char: '🍗', name: 'poultry leg' },
            { char: '🍘', name: 'rice cracker' },
            { char: '🍙', name: 'rice ball' },
            { char: '🍚', name: 'cooked rice' },
            { char: '🍛', name: 'curry rice' },
            { char: '🍜', name: 'steaming bowl' },
            { char: '🍝', name: 'spaghetti' },
            { char: '🍞', name: 'bread' },
            { char: '🍟', name: 'french fries' },
            { char: '🍠', name: 'roasted sweet potato' },
            { char: '🍡', name: 'dango' },
            { char: '🍢', name: 'oden' },
            { char: '🍣', name: 'sushi' },
            { char: '🍤', name: 'fried shrimp' },
            { char: '🍥', name: 'fish cake with swirl' },
            { char: '🍦', name: 'soft ice cream' },
            { char: '🍧', name: 'shaved ice' },
            { char: '🍨', name: 'ice cream' },
            { char: '🍩', name: 'doughnut' },
            { char: '🍪', name: 'cookie' },
            { char: '🍫', name: 'chocolate bar' },
            { char: '🍬', name: 'candy' },
            { char: '🍭', name: 'lollipop' },
            { char: '🍮', name: 'custard' },
            { char: '🍯', name: 'honey pot' },
            { char: '🍰', name: 'shortcake' },
            { char: '🍱', name: 'bento box' },
            { char: '🍲', name: 'pot of food' },
            { char: '🍳', name: 'cooking' },
            { char: '🍿', name: 'popcorn' },
            { char: '🥐', name: 'croissant' },
            { char: '🥓', name: 'bacon' },
            { char: '🥖', name: 'baguette bread' },
            { char: '🥗', name: 'green salad' },
            { char: '🥘', name: 'shallow pan of food' },
            { char: '🥙', name: 'stuffed flatbread' },
            { char: '🥚', name: 'egg' },
            { char: '🥜', name: 'peanuts' },
            { char: '🥞', name: 'pancakes' },
            { char: '🥟', name: 'dumpling' },
            { char: '🥠', name: 'fortune cookie' },
            { char: '🥡', name: 'takeout box' },
            { char: '🥣', name: 'bowl with spoon' },
            { char: '🥧', name: 'pie' },
            { char: '🥨', name: 'pretzel' },
            { char: '🥩', name: 'cut of meat' },
            { char: '🥪', name: 'sandwich' },
            { char: '🥫', name: 'canned food' },
            { char: '🥮', name: 'moon cake' },
            { char: '🥯', name: 'bagel' },
            { char: '🧀', name: 'cheese wedge' },
            { char: '🧁', name: 'cupcake' },
            { char: '🧆', name: 'falafel' },
            { char: '🧇', name: 'waffle' },
            { char: '🧈', name: 'butter' },
            { char: '🌽', name: 'ear of corn' },
            { char: '🌾', name: 'ear of rice' },
            { char: '🍄', name: 'mushroom' },
            { char: '🍅', name: 'tomato' },
            { char: '🍆', name: 'eggplant' },
            { char: '🥑', name: 'avocado' },
            { char: '🥒', name: 'cucumber' },
            { char: '🥔', name: 'potato' },
            { char: '🥕', name: 'carrot' },
            { char: '🥥', name: 'coconut' },
            { char: '🥦', name: 'broccoli' },
            { char: '🥬', name: 'leafy green' },
            { char: '🧄', name: 'garlic' },
            { char: '🧅', name: 'onion' },
            { char: '🍴', name: 'fork and knife' },
            { char: '🍽', name: 'fork and knife with plate' },
            { char: '🔪', name: 'kitchen knife' },
            { char: '🥄', name: 'spoon' },
            { char: '🥢', name: 'chopsticks' },
            { char: '🧂', name: 'salt' },
        ],
    },
    {
        name: "Activities",
        icon: "⚽",
        symbols: [
            { char: '⚽', name: 'soccer ball' },
            { char: '⚾', name: 'baseball' },
            { char: '🎣', name: 'fishing pole' },
            { char: '🎽', name: 'running shirt' },
            { char: '🎾', name: 'tennis' },
            { char: '🎿', name: 'skis' },
            { char: '🏀', name: 'basketball' },
            { char: '🏁', name: 'chequered flag' },
            { char: '🏂', name: 'snowboarder' },
            { char: '🏃', name: 'person running' },
            { char: '🏄', name: 'person surfing' },
            { char: '🏅', name: 'sports medal' },
            { char: '🏆', name: 'trophy' },
            { char: '🏇', name: 'horse racing' },
            { char: '🏈', name: 'american football' },
            { char: '🏉', name: 'rugby football' },
            { char: '🏊', name: 'person swimming' },
            { char: '🏋', name: 'person lifting weights' },
            { char: '🏌', name: 'person golfing' },
            { char: '🏏', name: 'cricket game' },
            { char: '🏐', name: 'volleyball' },
            { char: '🏑', name: 'field hockey' },
            { char: '🏒', name: 'ice hockey' },
            { char: '🏓', name: 'ping pong' },
            { char: '🏸', name: 'badminton' },
            { char: '🏹', name: 'bow and arrow' },
            { char: '🤸', name: 'person cartwheeling' },
            { char: '🤹', name: 'person juggling' },
            { char: '🤺', name: 'person fencing' },
            { char: '🤻', name: 'modern pentathlon' },
            { char: '🤼', name: 'people wrestling' },
            { char: '🤽', name: 'person playing water polo' },
            { char: '🤾', name: 'person playing handball' },
            { char: '🤿', name: 'diving mask' },
            { char: '🥅', name: 'goal net' },
            { char: '🥆', name: 'rifle' },
            { char: '🥇', name: '1st place medal' },
            { char: '🥈', name: '2nd place medal' },
            { char: '🥉', name: '3rd place medal' },
            { char: '🥊', name: 'boxing glove' },
            { char: '🥋', name: 'martial arts uniform' },
            { char: '🥌', name: 'curling stone' },
            { char: '🥍', name: 'lacrosse' },
            { char: '🥎', name: 'softball' },
            { char: '🥏', name: 'flying disc' },
            { char: '🎮', name: 'video game' },
            { char: '🎯', name: 'direct hit' },
            { char: '🎰', name: 'slot machine' },
            { char: '🎱', name: 'pool 8 ball' },
            { char: '🎲', name: 'game die' },
            { char: '🎳', name: 'bowling' },
            { char: '🎴', name: 'flower playing cards' },
            { char: '🧩', name: 'puzzle piece' },
            { char: '🎟', name: 'admission tickets' },
            { char: '🎠', name: 'carousel horse' },
            { char: '🎡', name: 'ferris wheel' },
            { char: '🎢', name: 'roller coaster' },
            { char: '🎨', name: 'artist palette' },
            { char: '🎪', name: 'circus tent' },
            { char: '🎫', name: 'ticket' },
            { char: '🎭', name: 'performing arts' },
            { char: '🪀', name: 'yo-yo' },
            { char: '🪁', name: 'kite' },
            { char: '🪂', name: 'parachute' },
            { char: '🪃', name: 'boomerang' },
            { char: '🪄', name: 'magic wand' },
            { char: '🪅', name: 'piñata' },
            { char: '🪆', name: 'nesting dolls' },
        ],
    },
    {
        name: "Travel & Places",
        icon: "✈️",
        symbols: [
            { char: '🚀', name: 'rocket' },
            { char: '🚁', name: 'helicopter' },
            { char: '🚂', name: 'locomotive' },
            { char: '🚃', name: 'railway car' },
            { char: '🚄', name: 'high-speed train' },
            { char: '🚅', name: 'bullet train' },
            { char: '🚆', name: 'train' },
            { char: '🚇', name: 'metro' },
            { char: '🚈', name: 'light rail' },
            { char: '🚉', name: 'station' },
            { char: '🚊', name: 'tram' },
            { char: '🚋', name: 'tram car' },
            { char: '🚌', name: 'bus' },
            { char: '🚍', name: 'oncoming bus' },
            { char: '🚎', name: 'trolleybus' },
            { char: '🚏', name: 'bus stop' },
            { char: '🚐', name: 'minibus' },
            { char: '🚑', name: 'ambulance' },
            { char: '🚒', name: 'fire engine' },
            { char: '🚓', name: 'police car' },
            { char: '🚔', name: 'oncoming police car' },
            { char: '🚕', name: 'taxi' },
            { char: '🚖', name: 'oncoming taxi' },
            { char: '🚗', name: 'automobile' },
            { char: '🚘', name: 'oncoming automobile' },
            { char: '🚙', name: 'recreational vehicle' },
            { char: '🚚', name: 'delivery truck' },
            { char: '🚛', name: 'articulated lorry' },
            { char: '🚜', name: 'tractor' },
            { char: '🚝', name: 'monorail' },
            { char: '🚞', name: 'mountain railway' },
            { char: '🚟', name: 'suspension railway' },
            { char: '🚠', name: 'mountain cableway' },
            { char: '🚡', name: 'aerial tramway' },
            { char: '🚢', name: 'ship' },
            { char: '🚣', name: 'person rowing boat' },
            { char: '🚤', name: 'speedboat' },
            { char: '🛴', name: 'kick scooter' },
            { char: '🛵', name: 'motor scooter' },
            { char: '🛶', name: 'canoe' },
            { char: '🛷', name: 'sled' },
            { char: '🛸', name: 'flying saucer' },
            { char: '🛺', name: 'auto rickshaw' },
            { char: '🛻', name: 'pickup truck' },
            { char: '🛼', name: 'roller skate' },
            { char: '⛲', name: 'fountain' },
            { char: '⛳', name: 'flag in hole' },
            { char: '⛺', name: 'tent' },
            { char: '⛽', name: 'fuel pump' },
            { char: '🌋', name: 'volcano' },
            { char: '🗺', name: 'world map' },
            { char: '🗻', name: 'mount fuji' },
            { char: '🗼', name: 'tokyo tower' },
            { char: '🗽', name: 'statue of liberty' },
            { char: '🗾', name: 'map of japan' },
            { char: '🗿', name: 'moai' },
            { char: '⛪', name: 'church' },
            { char: '🏠', name: 'house' },
            { char: '🏡', name: 'house with garden' },
            { char: '🏢', name: 'office building' },
            { char: '🏣', name: 'japanese post office' },
            { char: '🏤', name: 'post office' },
            { char: '🏥', name: 'hospital' },
            { char: '🏦', name: 'bank' },
            { char: '🏧', name: 'atm sign' },
            { char: '🏨', name: 'hotel' },
            { char: '🏩', name: 'love hotel' },
            { char: '🏪', name: 'convenience store' },
            { char: '🏫', name: 'school' },
            { char: '🏬', name: 'department store' },
            { char: '🏭', name: 'factory' },
            { char: '🏮', name: 'red paper lantern' },
            { char: '🏯', name: 'japanese castle' },
            { char: '🏰', name: 'castle' },
            { char: '🛕', name: 'hindu temple' },
            { char: '🏔', name: 'snow-capped mountain' },
            { char: '🏕', name: 'camping' },
            { char: '🏖', name: 'beach with umbrella' },
            { char: '🏗', name: 'building construction' },
            { char: '🏘', name: 'houses' },
            { char: '🏙', name: 'cityscape' },
            { char: '🏚', name: 'derelict house' },
            { char: '🏛', name: 'classical building' },
            { char: '🏜', name: 'desert' },
            { char: '🏝', name: 'desert island' },
            { char: '🏞', name: 'national park' },
            { char: '🏟', name: 'stadium' },
        ],
    },
    {
        name: "Objects",
        icon: "💡",
        symbols: [
            { char: '💌', name: 'love letter' },
            { char: '💒', name: 'wedding' },
            { char: '🎀', name: 'ribbon' },
            { char: '🎁', name: 'wrapped gift' },
            { char: '🎂', name: 'birthday cake' },
            { char: '🎃', name: 'jack-o-lantern' },
            { char: '🎄', name: 'christmas tree' },
            { char: '🎆', name: 'fireworks' },
            { char: '🎇', name: 'sparkler' },
            { char: '🎈', name: 'balloon' },
            { char: '🎉', name: 'party popper' },
            { char: '🎊', name: 'confetti ball' },
            { char: '🎋', name: 'tanabata tree' },
            { char: '🎌', name: 'crossed flags' },
            { char: '🎍', name: 'pine decoration' },
            { char: '🎎', name: 'japanese dolls' },
            { char: '🎏', name: 'carp streamer' },
            { char: '🎐', name: 'wind chime' },
            { char: '🎑', name: 'moon viewing ceremony' },
            { char: '🎒', name: 'school backpack' },
            { char: '🎓', name: 'graduation cap' },
            { char: '🎔', name: 'heart with tip' },
            { char: '🎕', name: 'bouquet' },
            { char: '🎖', name: 'military medal' },
            { char: '🎗', name: 'reminder ribbon' },
            { char: '🧧', name: 'red envelope' },
            { char: '🧨', name: 'firecracker' },
            { char: '💰', name: 'money bag' },
            { char: '💱', name: 'currency exchange' },
            { char: '💲', name: 'heavy dollar sign' },
            { char: '💳', name: 'credit card' },
            { char: '💴', name: 'yen banknote' },
            { char: '💵', name: 'dollar banknote' },
            { char: '💶', name: 'euro banknote' },
            { char: '💷', name: 'pound banknote' },
            { char: '💸', name: 'money with wings' },
            { char: '💹', name: 'chart increasing with yen' },
            { char: '📿', name: 'prayer beads' },
            { char: '💺', name: 'seat' },
            { char: '💻', name: 'laptop' },
            { char: '💼', name: 'briefcase' },
            { char: '💽', name: 'minidisc' },
            { char: '💾', name: 'floppy disk' },
            { char: '💿', name: 'optical disk' },
            { char: '📀', name: 'dvd' },
            { char: '📁', name: 'file folder' },
            { char: '📂', name: 'open file folder' },
            { char: '📃', name: 'page with curl' },
            { char: '📄', name: 'page facing up' },
            { char: '📅', name: 'calendar' },
            { char: '📆', name: 'tear-off calendar' },
            { char: '📇', name: 'card index' },
            { char: '📈', name: 'chart increasing' },
            { char: '📉', name: 'chart decreasing' },
            { char: '📊', name: 'bar chart' },
            { char: '📋', name: 'clipboard' },
            { char: '📌', name: 'pushpin' },
            { char: '📍', name: 'round pushpin' },
            { char: '📎', name: 'paperclip' },
            { char: '📏', name: 'straight ruler' },
            { char: '📐', name: 'triangular ruler' },
            { char: '📑', name: 'bookmark tabs' },
            { char: '📒', name: 'ledger' },
            { char: '📓', name: 'notebook' },
            { char: '📔', name: 'notebook with decorative cover' },
            { char: '📕', name: 'closed book' },
            { char: '📖', name: 'open book' },
            { char: '📗', name: 'green book' },
            { char: '📘', name: 'blue book' },
            { char: '📙', name: 'orange book' },
            { char: '📚', name: 'books' },
            { char: '📛', name: 'name badge' },
            { char: '📜', name: 'scroll' },
            { char: '📝', name: 'memo' },
            { char: '📞', name: 'telephone receiver' },
            { char: '📟', name: 'pager' },
            { char: '📠', name: 'fax machine' },
            { char: '📡', name: 'satellite antenna' },
            { char: '📢', name: 'loudspeaker' },
            { char: '📣', name: 'megaphone' },
            { char: '📤', name: 'outbox tray' },
            { char: '📥', name: 'inbox tray' },
            { char: '📰', name: 'newspaper' },
            { char: '🔋', name: 'battery' },
            { char: '🔌', name: 'electric plug' },
            { char: '🖇', name: 'linked paperclips' },
            { char: '🖈', name: 'black pushpin' },
            { char: '🖉', name: 'lower left pencil' },
            { char: '🖊', name: 'lower left ballpoint pen' },
            { char: '🖋', name: 'lower left fountain pen' },
            { char: '🖌', name: 'lower left paintbrush' },
            { char: '🖍', name: 'lower left crayon' },
            { char: '📱', name: 'mobile phone' },
            { char: '📲', name: 'mobile phone with arrow' },
            { char: '📳', name: 'vibration mode' },
            { char: '📴', name: 'mobile phone off' },
            { char: '📵', name: 'no mobile phones' },
            { char: '📶', name: 'antenna bars' },
        ],
    },
    {
        name: "Symbols",
        icon: "💯",
        symbols: [
            { char: '💯', name: 'hundred points' },
            { char: '🔲', name: 'black square button' },
            { char: '🔳', name: 'white square button' },
            { char: '🔴', name: 'red circle' },
            { char: '🔵', name: 'blue circle' },
            { char: '🔶', name: 'large orange diamond' },
            { char: '🔷', name: 'large blue diamond' },
            { char: '🔸', name: 'small orange diamond' },
            { char: '🔹', name: 'small blue diamond' },
            { char: '🔺', name: 'red triangle pointed up' },
            { char: '🔻', name: 'red triangle pointed down' },
            { char: '🔘', name: 'radio button' },
            { char: '🔙', name: 'BACK arrow' },
            { char: '🔚', name: 'END arrow' },
            { char: '🔛', name: 'ON! arrow' },
            { char: '🔜', name: 'SOON arrow' },
            { char: '🔝', name: 'TOP arrow' },
            { char: '🔞', name: 'no one under eighteen' },
            { char: '🔟', name: 'keycap: 10' },
            { char: '🔠', name: 'input latin uppercase' },
            { char: '🔡', name: 'input latin lowercase' },
            { char: '🔢', name: 'input numbers' },
            { char: '🔣', name: 'input symbols' },
            { char: '🔤', name: 'input latin letters' },
            { char: '🏻', name: 'light skin tone' },
            { char: '🏼', name: 'medium-light skin tone' },
            { char: '🏽', name: 'medium skin tone' },
            { char: '🏾', name: 'medium-dark skin tone' },
            { char: '🏿', name: 'dark skin tone' },
            { char: '💠', name: 'diamond with a dot' },
            { char: '💡', name: 'light bulb' },
            { char: '💢', name: 'anger symbol' },
            { char: '💣', name: 'bomb' },
            { char: '💥', name: 'collision' },
            { char: '💦', name: 'splashing sweat' },
            { char: '💧', name: 'droplet' },
            { char: '💨', name: 'dashing away' },
            { char: '🔔', name: 'bell' },
            { char: '🔕', name: 'bell with slash' },
            { char: '🔖', name: 'bookmark' },
            { char: '🔗', name: 'link' },
            { char: '🔥', name: 'fire' },
            { char: '🔫', name: 'pistol' },
            { char: '🔮', name: 'crystal ball' },
            { char: '🔰', name: 'japanese symbol for beginner' },
            { char: '🔱', name: 'trident emblem' },
            { char: '🧪', name: 'test tube' },
            { char: '🧫', name: 'petri dish' },
            { char: '🧬', name: 'dna' },
            { char: '🧮', name: 'abacus' },
            { char: '🧯', name: 'fire extinguisher' },
            { char: '🧱', name: 'brick' },
            { char: '🧳', name: 'luggage' },
            { char: '🧴', name: 'lotion bottle' },
            { char: '🧵', name: 'thread' },
            { char: '🧶', name: 'yarn' },
            { char: '🧷', name: 'safety pin' },
            { char: '🧸', name: 'teddy bear' },
            { char: '🧹', name: 'broom' },
            { char: '🧺', name: 'basket' },
            { char: '🧻', name: 'roll of paper' },
            { char: '🧼', name: 'soap' },
            { char: '🧽', name: 'sponge' },
            { char: '🧾', name: 'receipt' },
            { char: '🧿', name: 'nazar amulet' },
        ]
    }
];

export const allEmojiSymbols: EmojiSymbol[] = emojiCategories.flatMap(category => category.symbols);
